/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Achievement } from './achievement'

/**
 *
 * @export
 * @interface AchievementResponse
 */
export interface AchievementResponse {
  /**
   *
   * @type {Array<Achievement>}
   * @memberof AchievementResponse
   */
  allMonthLiveEventAchievements?: Array<Achievement>
  /**
   *
   * @type {Array<Achievement>}
   * @memberof AchievementResponse
   */
  challengeAchievements?: Array<Achievement>
  /**
   *
   * @type {Array<Achievement>}
   * @memberof AchievementResponse
   */
  courseAchievements?: Array<Achievement>
  /**
   *
   * @type {Achievement}
   * @memberof AchievementResponse
   */
  firstLiveEventAchievement?: Achievement
  /**
   *
   * @type {Array<Achievement>}
   * @memberof AchievementResponse
   */
  journalAchievements?: Array<Achievement>
  /**
   *
   * @type {Array<Achievement>}
   * @memberof AchievementResponse
   */
  lifeScoreAchievements?: Array<Achievement>
  /**
   *
   * @type {Achievement}
   * @memberof AchievementResponse
   */
  memberAchievement?: Achievement
  /**
   *
   * @type {Achievement}
   * @memberof AchievementResponse
   */
  referralAchievement?: Achievement
}
