/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AchievementCertificateResponse
 */
export interface AchievementCertificateResponse {
  /**
   *
   * @type {string}
   * @memberof AchievementCertificateResponse
   */
  achievementId?: string
  /**
   *
   * @type {string}
   * @memberof AchievementCertificateResponse
   */
  authorName?: string
  /**
   *
   * @type {string}
   * @memberof AchievementCertificateResponse
   */
  courseName?: string
  /**
   *
   * @type {string}
   * @memberof AchievementCertificateResponse
   */
  courseUrl?: string
  /**
   *
   * @type {number}
   * @memberof AchievementCertificateResponse
   */
  createTimestamp?: number
  /**
   *
   * @type {string}
   * @memberof AchievementCertificateResponse
   */
  date?: string
  /**
   *
   * @type {number}
   * @memberof AchievementCertificateResponse
   */
  deleteTimestamp?: number
  /**
   *
   * @type {string}
   * @memberof AchievementCertificateResponse
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof AchievementCertificateResponse
   */
  sourceId?: string
  /**
   *
   * @type {number}
   * @memberof AchievementCertificateResponse
   */
  updateTimestamp?: number
  /**
   *
   * @type {string}
   * @memberof AchievementCertificateResponse
   */
  url?: string
  /**
   *
   * @type {string}
   * @memberof AchievementCertificateResponse
   */
  userName?: string
  /**
   *
   * @type {string}
   * @memberof AchievementCertificateResponse
   */
  uuid?: string
}
