/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AchievementInProgress } from './achievement-in-progress'

/**
 *
 * @export
 * @interface AchievementInProgressResponse
 */
export interface AchievementInProgressResponse {
  /**
   *
   * @type {Array<AchievementInProgress>}
   * @memberof AchievementInProgressResponse
   */
  achievementInProgressList?: Array<AchievementInProgress>
  /**
   *
   * @type {number}
   * @memberof AchievementInProgressResponse
   */
  totalInProgressAchievement?: number
}
