/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CmsMedia } from './cms-media'

/**
 *
 * @export
 * @interface Achievement
 */
export interface Achievement {
  /**
   *
   * @type {number}
   * @memberof Achievement
   */
  achievementCount?: number
  /**
   *
   * @type {number}
   * @memberof Achievement
   */
  achievementLevel?: number
  /**
   *
   * @type {string}
   * @memberof Achievement
   */
  achievementName?: string
  /**
   *
   * @type {string}
   * @memberof Achievement
   */
  achievementType?: string
  /**
   *
   * @type {number}
   * @memberof Achievement
   */
  coinsEarned?: number
  /**
   *
   * @type {number}
   * @memberof Achievement
   */
  createTimestamp?: number
  /**
   *
   * @type {number}
   * @memberof Achievement
   */
  deleteTimestamp?: number
  /**
   *
   * @type {object}
   * @memberof Achievement
   */
  extraInfo?: object
  /**
   *
   * @type {string}
   * @memberof Achievement
   */
  groupId?: string
  /**
   *
   * @type {string}
   * @memberof Achievement
   */
  id?: string
  /**
   *
   * @type {CmsMedia}
   * @memberof Achievement
   */
  image?: CmsMedia
  /**
   *
   * @type {string}
   * @memberof Achievement
   */
  rewardType?: AchievementRewardTypeEnum
  /**
   *
   * @type {number}
   * @memberof Achievement
   */
  strapiId?: number
  /**
   *
   * @type {number}
   * @memberof Achievement
   */
  tierId?: number
  /**
   *
   * @type {string}
   * @memberof Achievement
   */
  trigger?: string
  /**
   *
   * @type {boolean}
   * @memberof Achievement
   */
  unread?: boolean
  /**
   *
   * @type {number}
   * @memberof Achievement
   */
  updateTimestamp?: number
  /**
   *
   * @type {string}
   * @memberof Achievement
   */
  url?: string
  /**
   *
   * @type {string}
   * @memberof Achievement
   */
  uuid?: string
}

export const AchievementRewardTypeEnum = {
  Badge: 'BADGE',
  Certificate: 'CERTIFICATE',
  Coin: 'COIN'
} as const

export type AchievementRewardTypeEnum = typeof AchievementRewardTypeEnum[keyof typeof AchievementRewardTypeEnum]
