/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AppInvitation
 */
export interface AppInvitation {
  /**
   *
   * @type {number}
   * @memberof AppInvitation
   */
  createTimestamp?: number
  /**
   *
   * @type {number}
   * @memberof AppInvitation
   */
  deleteTimestamp?: number
  /**
   *
   * @type {string}
   * @memberof AppInvitation
   */
  email?: string
  /**
   *
   * @type {string}
   * @memberof AppInvitation
   */
  firstName?: string
  /**
   *
   * @type {string}
   * @memberof AppInvitation
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof AppInvitation
   */
  lastName?: string
  /**
   *
   * @type {number}
   * @memberof AppInvitation
   */
  updateTimestamp?: number
}
