/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AppleValidateSubscription
 */
export interface AppleValidateSubscription {
  /**
   *
   * @type {Array<string>}
   * @memberof AppleValidateSubscription
   */
  originalTransactionIds?: Array<string>
  /**
   *
   * @type {string}
   * @memberof AppleValidateSubscription
   */
  transactionId?: string
}
