/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Achievement } from './achievement'
import { Assessment } from './assessment'
import { PostAssessmentCreationMessage } from './post-assessment-creation-message'

/**
 *
 * @export
 * @interface AssessmentResponse
 */
export interface AssessmentResponse {
  /**
   *
   * @type {Achievement}
   * @memberof AssessmentResponse
   */
  achievement?: Achievement
  /**
   *
   * @type {Assessment}
   * @memberof AssessmentResponse
   */
  assessment?: Assessment
  /**
   *
   * @type {number}
   * @memberof AssessmentResponse
   */
  coinsEarnedThisTime?: number
  /**
   *
   * @type {number}
   * @memberof AssessmentResponse
   */
  currentCoinCount?: number
  /**
   *
   * @type {PostAssessmentCreationMessage}
   * @memberof AssessmentResponse
   */
  message?: PostAssessmentCreationMessage
}
