/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AssignGrowthGroupLicenseRequest
 */
export interface AssignGrowthGroupLicenseRequest {
  /**
   *
   * @type {number}
   * @memberof AssignGrowthGroupLicenseRequest
   */
  allowedLimit?: number
  /**
   *
   * @type {number}
   * @memberof AssignGrowthGroupLicenseRequest
   */
  durationInDays?: number
  /**
   *
   * @type {string}
   * @memberof AssignGrowthGroupLicenseRequest
   */
  email?: string
  /**
   *
   * @type {boolean}
   * @memberof AssignGrowthGroupLicenseRequest
   */
  override?: boolean
  /**
   *
   * @type {number}
   * @memberof AssignGrowthGroupLicenseRequest
   */
  participantsAllowed?: number
}
