/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GrowthGroupInstance } from './growth-group-instance'

/**
 *
 * @export
 * @interface CancelGrowthGroupResponse
 */
export interface CancelGrowthGroupResponse {
  /**
   *
   * @type {{ [key: string]: string; }}
   * @memberof CancelGrowthGroupResponse
   */
  failureReason?: { [key: string]: string }
  /**
   *
   * @type {Array<GrowthGroupInstance>}
   * @memberof CancelGrowthGroupResponse
   */
  instanceList?: Array<GrowthGroupInstance>
}
