/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ChallengeUpsell
 */
export interface ChallengeUpsell {
  /**
   *
   * @type {number}
   * @memberof ChallengeUpsell
   */
  challengeId?: number
  /**
   *
   * @type {number}
   * @memberof ChallengeUpsell
   */
  createTimestamp?: number
  /**
   *
   * @type {number}
   * @memberof ChallengeUpsell
   */
  deleteTimestamp?: number
  /**
   *
   * @type {string}
   * @memberof ChallengeUpsell
   */
  id?: string
  /**
   *
   * @type {number}
   * @memberof ChallengeUpsell
   */
  updateTimestamp?: number
  /**
   *
   * @type {string}
   * @memberof ChallengeUpsell
   */
  userChallengeId?: string
  /**
   *
   * @type {string}
   * @memberof ChallengeUpsell
   */
  uuid?: string
}
