/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BaseEntity } from './base-entity'

/**
 *
 * @export
 * @interface ChallengeAssociatedRecord
 */
export interface ChallengeAssociatedRecord {
  /**
   *
   * @type {number}
   * @memberof ChallengeAssociatedRecord
   */
  challengeId?: number
  /**
   *
   * @type {number}
   * @memberof ChallengeAssociatedRecord
   */
  createTimestamp?: number
  /**
   *
   * @type {number}
   * @memberof ChallengeAssociatedRecord
   */
  customChallengeId?: number
  /**
   *
   * @type {number}
   * @memberof ChallengeAssociatedRecord
   */
  customTaskId?: number
  /**
   *
   * @type {number}
   * @memberof ChallengeAssociatedRecord
   */
  deleteTimestamp?: number
  /**
   *
   * @type {string}
   * @memberof ChallengeAssociatedRecord
   */
  id?: string
  /**
   *
   * @type {BaseEntity}
   * @memberof ChallengeAssociatedRecord
   */
  record?: BaseEntity
  /**
   *
   * @type {string}
   * @memberof ChallengeAssociatedRecord
   */
  recordObjectId?: string
  /**
   *
   * @type {string}
   * @memberof ChallengeAssociatedRecord
   */
  type?: ChallengeAssociatedRecordTypeEnum
  /**
   *
   * @type {number}
   * @memberof ChallengeAssociatedRecord
   */
  updateTimestamp?: number
  /**
   *
   * @type {string}
   * @memberof ChallengeAssociatedRecord
   */
  userChallengeId?: string
  /**
   *
   * @type {string}
   * @memberof ChallengeAssociatedRecord
   */
  uuid?: string
}

export const ChallengeAssociatedRecordTypeEnum = {
  Challenge: 'CHALLENGE',
  Journal: 'JOURNAL',
  Goal: 'GOAL',
  Plan: 'PLAN'
} as const

export type ChallengeAssociatedRecordTypeEnum =
  typeof ChallengeAssociatedRecordTypeEnum[keyof typeof ChallengeAssociatedRecordTypeEnum]
