/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Chat
 */
export interface Chat {
  /**
   *
   * @type {string}
   * @memberof Chat
   */
  chatId?: string
  /**
   *
   * @type {string}
   * @memberof Chat
   */
  message?: string
  /**
   *
   * @type {Array<string>}
   * @memberof Chat
   */
  recipientRoles?: Array<ChatRecipientRolesEnum>
  /**
   *
   * @type {string}
   * @memberof Chat
   */
  sender?: string
  /**
   *
   * @type {string}
   * @memberof Chat
   */
  senderName?: string
  /**
   *
   * @type {string}
   * @memberof Chat
   */
  senderRole?: ChatSenderRoleEnum
  /**
   *
   * @type {string}
   * @memberof Chat
   */
  time?: string
}

export const ChatRecipientRolesEnum = {
  Host: 'host',
  Attendee: 'attendee',
  CoHost: 'co-host',
  Speaker: 'speaker',
  Preview: 'preview',
  WaitingRoom: 'waiting-room'
} as const

export type ChatRecipientRolesEnum = typeof ChatRecipientRolesEnum[keyof typeof ChatRecipientRolesEnum]
export const ChatSenderRoleEnum = {
  Host: 'host',
  Attendee: 'attendee',
  CoHost: 'co-host',
  Speaker: 'speaker',
  Preview: 'preview',
  WaitingRoom: 'waiting-room'
} as const

export type ChatSenderRoleEnum = typeof ChatSenderRoleEnum[keyof typeof ChatSenderRoleEnum]
