/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CmsImage } from './cms-image'
import { CmsThumbnail2 } from './cms-thumbnail2'

/**
 *
 * @export
 * @interface CmsFormats1
 */
export interface CmsFormats1 {
  /**
   *
   * @type {CmsImage}
   * @memberof CmsFormats1
   */
  large?: CmsImage
  /**
   *
   * @type {CmsImage}
   * @memberof CmsFormats1
   */
  medium?: CmsImage
  /**
   *
   * @type {CmsImage}
   * @memberof CmsFormats1
   */
  small?: CmsImage
  /**
   *
   * @type {CmsThumbnail2}
   * @memberof CmsFormats1
   */
  thumbnail?: CmsThumbnail2
}
