/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CmsEvents
 */
export interface CmsEvents {
  /**
   *
   * @type {string}
   * @memberof CmsEvents
   */
  name?: string
  /**
   *
   * @type {string}
   * @memberof CmsEvents
   */
  trigger?: CmsEventsTriggerEnum
  /**
   *
   * @type {string}
   * @memberof CmsEvents
   */
  type?: CmsEventsTypeEnum
}

export const CmsEventsTriggerEnum = {
  Signup: 'SIGNUP',
  Payment: 'PAYMENT'
} as const

export type CmsEventsTriggerEnum = typeof CmsEventsTriggerEnum[keyof typeof CmsEventsTriggerEnum]
export const CmsEventsTypeEnum = {
  Facebook: 'FACEBOOK',
  Google: 'GOOGLE',
  Bing: 'BING',
  Appsflyer: 'APPSFLYER',
  Mixpanel: 'MIXPANEL'
} as const

export type CmsEventsTypeEnum = typeof CmsEventsTypeEnum[keyof typeof CmsEventsTypeEnum]
