/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CmsChallenge } from './cms-challenge'
import { CmsCourse } from './cms-course'

/**
 *
 * @export
 * @interface CmsBulletItem
 */
export interface CmsBulletItem {
  /**
   *
   * @type {CmsChallenge}
   * @memberof CmsBulletItem
   */
  challenge?: CmsChallenge
  /**
   *
   * @type {CmsCourse}
   * @memberof CmsBulletItem
   */
  course?: CmsCourse
  /**
   *
   * @type {string}
   * @memberof CmsBulletItem
   */
  iconUrl?: string
  /**
   *
   * @type {number}
   * @memberof CmsBulletItem
   */
  id?: number
  /**
   *
   * @type {string}
   * @memberof CmsBulletItem
   */
  linkText?: string
  /**
   *
   * @type {string}
   * @memberof CmsBulletItem
   */
  title?: string
  /**
   *
   * @type {string}
   * @memberof CmsBulletItem
   */
  type?: string
}
