/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CmsMarketingWebhook
 */
export interface CmsMarketingWebhook {
  /**
   *
   * @type {string}
   * @memberof CmsMarketingWebhook
   */
  trigger?: CmsMarketingWebhookTriggerEnum
  /**
   *
   * @type {string}
   * @memberof CmsMarketingWebhook
   */
  type?: CmsMarketingWebhookTypeEnum
  /**
   *
   * @type {string}
   * @memberof CmsMarketingWebhook
   */
  url?: string
}

export const CmsMarketingWebhookTriggerEnum = {
  Signup: 'SIGNUP',
  Payment: 'PAYMENT'
} as const

export type CmsMarketingWebhookTriggerEnum =
  typeof CmsMarketingWebhookTriggerEnum[keyof typeof CmsMarketingWebhookTriggerEnum]
export const CmsMarketingWebhookTypeEnum = {
  Kajabi: 'KAJABI',
  Proof: 'PROOF'
} as const

export type CmsMarketingWebhookTypeEnum = typeof CmsMarketingWebhookTypeEnum[keyof typeof CmsMarketingWebhookTypeEnum]
