/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CmsMedia } from './cms-media'

/**
 *
 * @export
 * @interface CmsTier
 */
export interface CmsTier {
  /**
   *
   * @type {CmsMedia}
   * @memberof CmsTier
   */
  completedBadge?: CmsMedia
  /**
   *
   * @type {number}
   * @memberof CmsTier
   */
  id?: number
  /**
   *
   * @type {string}
   * @memberof CmsTier
   */
  name?: string
  /**
   *
   * @type {number}
   * @memberof CmsTier
   */
  rewardAmount?: number
  /**
   *
   * @type {number}
   * @memberof CmsTier
   */
  threshold?: number
}
