/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CmsOfferPlan
 */
export interface CmsOfferPlan {
  /**
   *
   * @type {boolean}
   * @memberof CmsOfferPlan
   */
  BASIC_YEAR?: boolean
  /**
   *
   * @type {boolean}
   * @memberof CmsOfferPlan
   */
  MASTERY_MONTH?: boolean
  /**
   *
   * @type {string}
   * @memberof CmsOfferPlan
   */
  MASTERY_YEAR?: string
  /**
   *
   * @type {number}
   * @memberof CmsOfferPlan
   */
  id?: number
}
