/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CmsImage } from './cms-image'

/**
 *
 * @export
 * @interface CmsOnboard
 */
export interface CmsOnboard {
  /**
   *
   * @type {string}
   * @memberof CmsOnboard
   */
  buttonText?: string
  /**
   *
   * @type {string}
   * @memberof CmsOnboard
   */
  description?: string
  /**
   *
   * @type {string}
   * @memberof CmsOnboard
   */
  heading?: string
  /**
   *
   * @type {number}
   * @memberof CmsOnboard
   */
  id?: number
  /**
   *
   * @type {CmsImage}
   * @memberof CmsOnboard
   */
  image?: CmsImage
  /**
   *
   * @type {string}
   * @memberof CmsOnboard
   */
  videoUrl?: string
}
