/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CmsOnboard } from './cms-onboard'
import { CmsTooltip } from './cms-tooltip'

/**
 *
 * @export
 * @interface CmsSubscriptionPlan
 */
export interface CmsSubscriptionPlan {
  /**
   *
   * @type {object}
   * @memberof CmsSubscriptionPlan
   */
  amount?: object
  /**
   *
   * @type {string}
   * @memberof CmsSubscriptionPlan
   */
  appleMonthlyProductId?: string
  /**
   *
   * @type {string}
   * @memberof CmsSubscriptionPlan
   */
  appleYearlyProductId?: string
  /**
   *
   * @type {string}
   * @memberof CmsSubscriptionPlan
   */
  bulletPoints?: string
  /**
   *
   * @type {string}
   * @memberof CmsSubscriptionPlan
   */
  created_at?: string
  /**
   *
   * @type {string}
   * @memberof CmsSubscriptionPlan
   */
  currency?: string
  /**
   *
   * @type {string}
   * @memberof CmsSubscriptionPlan
   */
  description?: string
  /**
   *
   * @type {number}
   * @memberof CmsSubscriptionPlan
   */
  id?: number
  /**
   *
   * @type {string}
   * @memberof CmsSubscriptionPlan
   */
  level?: string
  /**
   *
   * @type {number}
   * @memberof CmsSubscriptionPlan
   */
  levelWeight?: number
  /**
   *
   * @type {number}
   * @memberof CmsSubscriptionPlan
   */
  monthlyAmount?: number
  /**
   *
   * @type {string}
   * @memberof CmsSubscriptionPlan
   */
  name?: string
  /**
   *
   * @type {number}
   * @memberof CmsSubscriptionPlan
   */
  offer?: number
  /**
   *
   * @type {CmsOnboard}
   * @memberof CmsSubscriptionPlan
   */
  onboarding?: CmsOnboard
  /**
   *
   * @type {string}
   * @memberof CmsSubscriptionPlan
   */
  paypalMonthlyPriceId?: string
  /**
   *
   * @type {string}
   * @memberof CmsSubscriptionPlan
   */
  paypalYearlyPriceId?: string
  /**
   *
   * @type {string}
   * @memberof CmsSubscriptionPlan
   */
  stripeMonthlyPriceId?: string
  /**
   *
   * @type {string}
   * @memberof CmsSubscriptionPlan
   */
  stripeYearlyPriceId?: string
  /**
   *
   * @type {Array<CmsTooltip>}
   * @memberof CmsSubscriptionPlan
   */
  tooltips?: Array<CmsTooltip>
  /**
   *
   * @type {string}
   * @memberof CmsSubscriptionPlan
   */
  updated_at?: string
  /**
   *
   * @type {number}
   * @memberof CmsSubscriptionPlan
   */
  yearlyAmount?: number
}
