/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CmsOfferLicense
 */
export interface CmsOfferLicense {
  /**
   *
   * @type {boolean}
   * @memberof CmsOfferLicense
   */
  AUDIO_COURSE_ALL_ACCESS?: boolean
  /**
   *
   * @type {boolean}
   * @memberof CmsOfferLicense
   */
  AUDIO_COURSE_LIMITED_ACCESS?: boolean
  /**
   *
   * @type {boolean}
   * @memberof CmsOfferLicense
   */
  CHALLENGE_ALL_ACCESS?: boolean
  /**
   *
   * @type {boolean}
   * @memberof CmsOfferLicense
   */
  CHALLENGE_LIMITED_ACCESS?: boolean
  /**
   *
   * @type {boolean}
   * @memberof CmsOfferLicense
   */
  CourseAllAccess?: boolean
  /**
   *
   * @type {boolean}
   * @memberof CmsOfferLicense
   */
  EVENT_ALL_ACCESS?: boolean
  /**
   *
   * @type {boolean}
   * @memberof CmsOfferLicense
   */
  EVENT_LIMITED_ACCESS?: boolean
  /**
   *
   * @type {boolean}
   * @memberof CmsOfferLicense
   */
  GOAL_ALL_ACCESS?: boolean
  /**
   *
   * @type {boolean}
   * @memberof CmsOfferLicense
   */
  GOAL_LIMITED_ACCESS?: boolean
  /**
   *
   * @type {boolean}
   * @memberof CmsOfferLicense
   */
  JOURNAL_ALL_ACCESS?: boolean
  /**
   *
   * @type {boolean}
   * @memberof CmsOfferLicense
   */
  JOURNAL_LIMITED_ACCESS?: boolean
  /**
   *
   * @type {boolean}
   * @memberof CmsOfferLicense
   */
  LIFESCORE_ALL_ACCESS?: boolean
  /**
   *
   * @type {boolean}
   * @memberof CmsOfferLicense
   */
  LIFESCORE_LIMITED_ACCESS?: boolean
  /**
   *
   * @type {boolean}
   * @memberof CmsOfferLicense
   */
  PLAN_ALL_ACCESS?: boolean
  /**
   *
   * @type {boolean}
   * @memberof CmsOfferLicense
   */
  PLAN_LIMITED_ACCESS?: boolean
  /**
   *
   * @type {boolean}
   * @memberof CmsOfferLicense
   */
  VIDEO_COURSE_ALL_ACCESS?: boolean
  /**
   *
   * @type {boolean}
   * @memberof CmsOfferLicense
   */
  VIDEO_COURSE_LIMITED_ACCESS?: boolean
  /**
   *
   * @type {number}
   * @memberof CmsOfferLicense
   */
  id?: number
}
