/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CmsBulletItem } from './cms-bullet-item'
import { CmsEvents } from './cms-events'
import { CmsMarketingWebhook } from './cms-marketing-webhook'
import { CmsMedia } from './cms-media'
import { CmsOffer2 } from './cms-offer2'
import { CmsOfferChallenge } from './cms-offer-challenge'
import { CmsOfferCourse2 } from './cms-offer-course2'
import { CmsOfferLicense } from './cms-offer-license'
import { CmsOfferPlan } from './cms-offer-plan'
import { CmsOnboard } from './cms-onboard'
import { CmsSubscriptionPlan } from './cms-subscription-plan'
import { CmsThumbnail2 } from './cms-thumbnail2'
import { CmsTooltip } from './cms-tooltip'

/**
 *
 * @export
 * @interface CmsOffer1
 */
export interface CmsOffer1 {
  /**
   *
   * @type {string}
   * @memberof CmsOffer1
   */
  applePlanId?: string
  /**
   *
   * @type {CmsMedia}
   * @memberof CmsOffer1
   */
  badge?: CmsMedia
  /**
   *
   * @type {Array<CmsBulletItem>}
   * @memberof CmsOffer1
   */
  bulletItems?: Array<CmsBulletItem>
  /**
   *
   * @type {CmsOffer2}
   * @memberof CmsOffer1
   */
  canonical?: CmsOffer2
  /**
   *
   * @type {CmsOfferChallenge}
   * @memberof CmsOffer1
   */
  challenge?: CmsOfferChallenge
  /**
   *
   * @type {string}
   * @memberof CmsOffer1
   */
  changeToPlan?: string
  /**
   *
   * @type {Array<CmsOfferCourse2>}
   * @memberof CmsOffer1
   */
  courses?: Array<CmsOfferCourse2>
  /**
   *
   * @type {string}
   * @memberof CmsOffer1
   */
  created_at?: string
  /**
   *
   * @type {string}
   * @memberof CmsOffer1
   */
  currency?: string
  /**
   *
   * @type {CmsMedia}
   * @memberof CmsOffer1
   */
  dashboardThumbnail?: CmsMedia
  /**
   *
   * @type {CmsMedia}
   * @memberof CmsOffer1
   */
  dashboardThumbnailVertical?: CmsMedia
  /**
   *
   * @type {string}
   * @memberof CmsOffer1
   */
  description?: string
  /**
   *
   * @type {string}
   * @memberof CmsOffer1
   */
  emailTemplateId?: string
  /**
   *
   * @type {Array<CmsEvents>}
   * @memberof CmsOffer1
   */
  events?: Array<CmsEvents>
  /**
   *
   * @type {object}
   * @memberof CmsOffer1
   */
  helpText?: object
  /**
   *
   * @type {number}
   * @memberof CmsOffer1
   */
  id?: number
  /**
   *
   * @type {CmsThumbnail2}
   * @memberof CmsOffer1
   */
  image?: CmsThumbnail2
  /**
   *
   * @type {string}
   * @memberof CmsOffer1
   */
  interval?: string
  /**
   *
   * @type {string}
   * @memberof CmsOffer1
   */
  kajabiOfferId?: string
  /**
   *
   * @type {CmsOfferLicense}
   * @memberof CmsOffer1
   */
  licenses?: CmsOfferLicense
  /**
   *
   * @type {CmsOnboard}
   * @memberof CmsOffer1
   */
  onboarding?: CmsOnboard
  /**
   *
   * @type {number}
   * @memberof CmsOffer1
   */
  order?: number
  /**
   *
   * @type {string}
   * @memberof CmsOffer1
   */
  paypalPlanId?: string
  /**
   *
   * @type {CmsOfferPlan}
   * @memberof CmsOffer1
   */
  plan?: CmsOfferPlan
  /**
   *
   * @type {number}
   * @memberof CmsOffer1
   */
  price?: number
  /**
   *
   * @type {string}
   * @memberof CmsOffer1
   */
  published_at?: string
  /**
   *
   * @type {string}
   * @memberof CmsOffer1
   */
  purchaseButtonText?: string
  /**
   *
   * @type {boolean}
   * @memberof CmsOffer1
   */
  recommended?: boolean
  /**
   *
   * @type {boolean}
   * @memberof CmsOffer1
   */
  showInMembershipArea?: boolean
  /**
   *
   * @type {string}
   * @memberof CmsOffer1
   */
  signupDescription?: string
  /**
   *
   * @type {string}
   * @memberof CmsOffer1
   */
  slug?: string
  /**
   *
   * @type {boolean}
   * @memberof CmsOffer1
   */
  specialOffer?: boolean
  /**
   *
   * @type {string}
   * @memberof CmsOffer1
   */
  stripePlanId?: string
  /**
   *
   * @type {Array<CmsSubscriptionPlan>}
   * @memberof CmsOffer1
   */
  subscriptionPlans?: Array<CmsSubscriptionPlan>
  /**
   *
   * @type {string}
   * @memberof CmsOffer1
   */
  subtitle?: string
  /**
   *
   * @type {CmsThumbnail2}
   * @memberof CmsOffer1
   */
  thumbnail?: CmsThumbnail2
  /**
   *
   * @type {string}
   * @memberof CmsOffer1
   */
  title?: string
  /**
   *
   * @type {string}
   * @memberof CmsOffer1
   */
  titleNoCoins?: string
  /**
   *
   * @type {Array<CmsTooltip>}
   * @memberof CmsOffer1
   */
  tooltips?: Array<CmsTooltip>
  /**
   *
   * @type {string}
   * @memberof CmsOffer1
   */
  type?: string
  /**
   *
   * @type {string}
   * @memberof CmsOffer1
   */
  updated_at?: string
  /**
   *
   * @type {object}
   * @memberof CmsOffer1
   */
  videoUrl?: object
  /**
   *
   * @type {Array<CmsMarketingWebhook>}
   * @memberof CmsOffer1
   */
  webhooks?: Array<CmsMarketingWebhook>
}
