/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CmsMedia } from './cms-media'

/**
 *
 * @export
 * @interface CmsCourseOffer
 */
export interface CmsCourseOffer {
  /**
   *
   * @type {Array<CmsMedia>}
   * @memberof CmsCourseOffer
   */
  background?: Array<CmsMedia>
  /**
   *
   * @type {string}
   * @memberof CmsCourseOffer
   */
  created_at?: string
  /**
   *
   * @type {string}
   * @memberof CmsCourseOffer
   */
  description?: string
  /**
   *
   * @type {number}
   * @memberof CmsCourseOffer
   */
  id?: number
  /**
   *
   * @type {string}
   * @memberof CmsCourseOffer
   */
  link?: string
  /**
   *
   * @type {string}
   * @memberof CmsCourseOffer
   */
  linkDescription?: string
  /**
   *
   * @type {string}
   * @memberof CmsCourseOffer
   */
  published_at?: string
  /**
   *
   * @type {string}
   * @memberof CmsCourseOffer
   */
  shortDescription?: string
  /**
   *
   * @type {string}
   * @memberof CmsCourseOffer
   */
  title?: string
  /**
   *
   * @type {string}
   * @memberof CmsCourseOffer
   */
  updated_at?: string
  /**
   *
   * @type {string}
   * @memberof CmsCourseOffer
   */
  videoLink?: string
}
