/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CmsImage
 */
export interface CmsImage {
  /**
   *
   * @type {string}
   * @memberof CmsImage
   */
  ext?: string
  /**
   *
   * @type {string}
   * @memberof CmsImage
   */
  hash?: string
  /**
   *
   * @type {number}
   * @memberof CmsImage
   */
  height?: number
  /**
   *
   * @type {string}
   * @memberof CmsImage
   */
  mime?: string
  /**
   *
   * @type {string}
   * @memberof CmsImage
   */
  name?: string
  /**
   *
   * @type {object}
   * @memberof CmsImage
   */
  path?: object
  /**
   *
   * @type {number}
   * @memberof CmsImage
   */
  size?: number
  /**
   *
   * @type {string}
   * @memberof CmsImage
   */
  url?: string
  /**
   *
   * @type {number}
   * @memberof CmsImage
   */
  width?: number
}
