/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CmsOffer } from './cms-offer'
import { CmsOfferLicense } from './cms-offer-license'
import { CmsOnboard } from './cms-onboard'
import { CmsTooltip } from './cms-tooltip'

/**
 *
 * @export
 * @interface CmsSubscriptionPlan1
 */
export interface CmsSubscriptionPlan1 {
  /**
   *
   * @type {string}
   * @memberof CmsSubscriptionPlan1
   */
  amount?: string
  /**
   *
   * @type {string}
   * @memberof CmsSubscriptionPlan1
   */
  appleMonthlyProductId?: string
  /**
   *
   * @type {string}
   * @memberof CmsSubscriptionPlan1
   */
  appleYearlyProductId?: string
  /**
   *
   * @type {string}
   * @memberof CmsSubscriptionPlan1
   */
  bulletPoints?: string
  /**
   *
   * @type {string}
   * @memberof CmsSubscriptionPlan1
   */
  currency?: string
  /**
   *
   * @type {string}
   * @memberof CmsSubscriptionPlan1
   */
  description?: string
  /**
   *
   * @type {boolean}
   * @memberof CmsSubscriptionPlan1
   */
  enterprise?: boolean
  /**
   *
   * @type {Array<CmsOffer>}
   * @memberof CmsSubscriptionPlan1
   */
  freeOffers?: Array<CmsOffer>
  /**
   *
   * @type {number}
   * @memberof CmsSubscriptionPlan1
   */
  id?: number
  /**
   *
   * @type {string}
   * @memberof CmsSubscriptionPlan1
   */
  level?: string
  /**
   *
   * @type {number}
   * @memberof CmsSubscriptionPlan1
   */
  levelWeight?: number
  /**
   *
   * @type {CmsOfferLicense}
   * @memberof CmsSubscriptionPlan1
   */
  licenses?: CmsOfferLicense
  /**
   *
   * @type {number}
   * @memberof CmsSubscriptionPlan1
   */
  monthlyAmount?: number
  /**
   *
   * @type {string}
   * @memberof CmsSubscriptionPlan1
   */
  name?: string
  /**
   *
   * @type {CmsOnboard}
   * @memberof CmsSubscriptionPlan1
   */
  onboarding?: CmsOnboard
  /**
   *
   * @type {string}
   * @memberof CmsSubscriptionPlan1
   */
  paypalMonthlyPriceId?: string
  /**
   *
   * @type {string}
   * @memberof CmsSubscriptionPlan1
   */
  paypalYearlyPriceId?: string
  /**
   *
   * @type {string}
   * @memberof CmsSubscriptionPlan1
   */
  stripeMonthlyPriceId?: string
  /**
   *
   * @type {string}
   * @memberof CmsSubscriptionPlan1
   */
  stripeYearlyPriceId?: string
  /**
   *
   * @type {Array<CmsTooltip>}
   * @memberof CmsSubscriptionPlan1
   */
  tooltips?: Array<CmsTooltip>
  /**
   *
   * @type {string}
   * @memberof CmsSubscriptionPlan1
   */
  withoutTrialAppleMonthlyProductId?: string
  /**
   *
   * @type {string}
   * @memberof CmsSubscriptionPlan1
   */
  withoutTrialAppleYearlyProductId?: string
  /**
   *
   * @type {string}
   * @memberof CmsSubscriptionPlan1
   */
  withoutTrialPaypalMonthlyPriceId?: string
  /**
   *
   * @type {string}
   * @memberof CmsSubscriptionPlan1
   */
  withoutTrialPaypalYearlyPriceId?: string
  /**
   *
   * @type {string}
   * @memberof CmsSubscriptionPlan1
   */
  withoutTrialStripeMonthlyPriceId?: string
  /**
   *
   * @type {string}
   * @memberof CmsSubscriptionPlan1
   */
  withoutTrialStripeYearlyPriceId?: string
  /**
   *
   * @type {number}
   * @memberof CmsSubscriptionPlan1
   */
  yearlyAmount?: number
}
