/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CmsImage } from './cms-image'
import { CmsMedia } from './cms-media'
import { CmsOfferLicense } from './cms-offer-license'
import { CmsTier } from './cms-tier'
import { CmsTooltip } from './cms-tooltip'
import { CustomChallenge } from './custom-challenge'
import { PremiereDateCountdown } from './premiere-date-countdown'

/**
 *
 * @export
 * @interface CmsChallenge
 */
export interface CmsChallenge {
  /**
   *
   * @type {boolean}
   * @memberof CmsChallenge
   */
  beforePremiereDate?: boolean
  /**
   *
   * @type {string}
   * @memberof CmsChallenge
   */
  challengeEndDate?: string
  /**
   *
   * @type {CmsMedia}
   * @memberof CmsChallenge
   */
  completedBadge?: CmsMedia
  /**
   *
   * @type {string}
   * @memberof CmsChallenge
   */
  created_at?: string
  /**
   *
   * @type {Array<CustomChallenge>}
   * @memberof CmsChallenge
   */
  customChallenge?: Array<CustomChallenge>
  /**
   *
   * @type {CmsMedia}
   * @memberof CmsChallenge
   */
  customIcon?: CmsMedia
  /**
   *
   * @type {CmsMedia}
   * @memberof CmsChallenge
   */
  dashboardThumbnail?: CmsMedia
  /**
   *
   * @type {CmsMedia}
   * @memberof CmsChallenge
   */
  dashboardThumbnailVertical?: CmsMedia
  /**
   *
   * @type {string}
   * @memberof CmsChallenge
   */
  description?: string
  /**
   *
   * @type {string}
   * @memberof CmsChallenge
   */
  endDate?: string
  /**
   *
   * @type {boolean}
   * @memberof CmsChallenge
   */
  evergreenChallenge?: boolean
  /**
   *
   * @type {boolean}
   * @memberof CmsChallenge
   */
  free?: boolean
  /**
   *
   * @type {number}
   * @memberof CmsChallenge
   */
  id?: number
  /**
   *
   * @type {CmsImage}
   * @memberof CmsChallenge
   */
  image?: CmsImage
  /**
   *
   * @type {boolean}
   * @memberof CmsChallenge
   */
  isFree?: boolean
  /**
   *
   * @type {CmsOfferLicense}
   * @memberof CmsChallenge
   */
  licenses?: CmsOfferLicense
  /**
   *
   * @type {number}
   * @memberof CmsChallenge
   */
  maxTierValue?: number
  /**
   *
   * @type {number}
   * @memberof CmsChallenge
   */
  numberOfDaysInChallenge?: number
  /**
   *
   * @type {number}
   * @memberof CmsChallenge
   */
  numberOfDaysRemaining?: number
  /**
   *
   * @type {PremiereDateCountdown}
   * @memberof CmsChallenge
   */
  premiereDateCountdown?: PremiereDateCountdown
  /**
   *
   * @type {number}
   * @memberof CmsChallenge
   */
  registrationCount?: number
  /**
   *
   * @type {string}
   * @memberof CmsChallenge
   */
  shortDescription?: string
  /**
   *
   * @type {string}
   * @memberof CmsChallenge
   */
  signupDescription?: string
  /**
   *
   * @type {string}
   * @memberof CmsChallenge
   */
  signupHeading?: string
  /**
   *
   * @type {string}
   * @memberof CmsChallenge
   */
  signupVideoUrl?: string
  /**
   *
   * @type {string}
   * @memberof CmsChallenge
   */
  startDate?: string
  /**
   *
   * @type {Array<CmsTier>}
   * @memberof CmsChallenge
   */
  tiers?: Array<CmsTier>
  /**
   *
   * @type {string}
   * @memberof CmsChallenge
   */
  title?: string
  /**
   *
   * @type {string}
   * @memberof CmsChallenge
   */
  titleUid?: string
  /**
   *
   * @type {Array<CmsTooltip>}
   * @memberof CmsChallenge
   */
  tooltips?: Array<CmsTooltip>
  /**
   *
   * @type {string}
   * @memberof CmsChallenge
   */
  type?: CmsChallengeTypeEnum
  /**
   *
   * @type {string}
   * @memberof CmsChallenge
   */
  updated_at?: string
  /**
   *
   * @type {string}
   * @memberof CmsChallenge
   */
  welcomeDescription?: string
  /**
   *
   * @type {CmsMedia}
   * @memberof CmsChallenge
   */
  welcomeImage?: CmsMedia
  /**
   *
   * @type {string}
   * @memberof CmsChallenge
   */
  welcomePrimaryButtonText?: string
  /**
   *
   * @type {string}
   * @memberof CmsChallenge
   */
  welcomeTitle?: string
  /**
   *
   * @type {string}
   * @memberof CmsChallenge
   */
  welcomeVideoUrl?: string
}

export const CmsChallengeTypeEnum = {
  Journal: 'Journal',
  DailyHabit: 'DailyHabit',
  WeeklyHabit: 'WeeklyHabit',
  MonthlyHabit: 'MonthlyHabit',
  Custom: 'Custom'
} as const

export type CmsChallengeTypeEnum = typeof CmsChallengeTypeEnum[keyof typeof CmsChallengeTypeEnum]
