/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CmsContentTag
 */
export interface CmsContentTag {
  /**
   *
   * @type {string}
   * @memberof CmsContentTag
   */
  UID?: string
  /**
   *
   * @type {string}
   * @memberof CmsContentTag
   */
  created_at?: string
  /**
   *
   * @type {number}
   * @memberof CmsContentTag
   */
  id?: number
  /**
   *
   * @type {string}
   * @memberof CmsContentTag
   */
  name?: string
  /**
   *
   * @type {number}
   * @memberof CmsContentTag
   */
  order?: number
  /**
   *
   * @type {string}
   * @memberof CmsContentTag
   */
  tagId?: string
  /**
   *
   * @type {string}
   * @memberof CmsContentTag
   */
  updated_at?: string
}
