/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CmsFormats } from './cms-formats'

/**
 *
 * @export
 * @interface CmsThumbnail
 */
export interface CmsThumbnail {
  /**
   *
   * @type {string}
   * @memberof CmsThumbnail
   */
  alternativeText?: string
  /**
   *
   * @type {string}
   * @memberof CmsThumbnail
   */
  caption?: string
  /**
   *
   * @type {string}
   * @memberof CmsThumbnail
   */
  created_at?: string
  /**
   *
   * @type {string}
   * @memberof CmsThumbnail
   */
  ext?: string
  /**
   *
   * @type {CmsFormats}
   * @memberof CmsThumbnail
   */
  formats?: CmsFormats
  /**
   *
   * @type {string}
   * @memberof CmsThumbnail
   */
  hash?: string
  /**
   *
   * @type {number}
   * @memberof CmsThumbnail
   */
  height?: number
  /**
   *
   * @type {number}
   * @memberof CmsThumbnail
   */
  id?: number
  /**
   *
   * @type {string}
   * @memberof CmsThumbnail
   */
  mime?: string
  /**
   *
   * @type {string}
   * @memberof CmsThumbnail
   */
  name?: string
  /**
   *
   * @type {object}
   * @memberof CmsThumbnail
   */
  path?: object
  /**
   *
   * @type {object}
   * @memberof CmsThumbnail
   */
  previewUrl?: object
  /**
   *
   * @type {string}
   * @memberof CmsThumbnail
   */
  provider?: string
  /**
   *
   * @type {object}
   * @memberof CmsThumbnail
   */
  provider_metadata?: object
  /**
   *
   * @type {number}
   * @memberof CmsThumbnail
   */
  size?: number
  /**
   *
   * @type {string}
   * @memberof CmsThumbnail
   */
  updated_at?: string
  /**
   *
   * @type {string}
   * @memberof CmsThumbnail
   */
  url?: string
  /**
   *
   * @type {number}
   * @memberof CmsThumbnail
   */
  width?: number
}
