/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CmsImage } from './cms-image'

/**
 *
 * @export
 * @interface CmsTooltipItem
 */
export interface CmsTooltipItem {
  /**
   *
   * @type {string}
   * @memberof CmsTooltipItem
   */
  created_at?: string
  /**
   *
   * @type {string}
   * @memberof CmsTooltipItem
   */
  description?: string
  /**
   *
   * @type {string}
   * @memberof CmsTooltipItem
   */
  element?: string
  /**
   *
   * @type {string}
   * @memberof CmsTooltipItem
   */
  id?: string
  /**
   *
   * @type {CmsImage}
   * @memberof CmsTooltipItem
   */
  image?: CmsImage
  /**
   *
   * @type {string}
   * @memberof CmsTooltipItem
   */
  nextButtonLabel?: string
  /**
   *
   * @type {number}
   * @memberof CmsTooltipItem
   */
  order?: number
  /**
   *
   * @type {string}
   * @memberof CmsTooltipItem
   */
  position?: string
  /**
   *
   * @type {string}
   * @memberof CmsTooltipItem
   */
  previousButtonLabel?: string
  /**
   *
   * @type {string}
   * @memberof CmsTooltipItem
   */
  title?: string
}
