/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Plan } from './plan'

/**
 *
 * @export
 * @interface CompletedPlansList
 */
export interface CompletedPlansList {
  /**
   *
   * @type {number}
   * @memberof CompletedPlansList
   */
  count?: number
  /**
   *
   * @type {Array<Plan>}
   * @memberof CompletedPlansList
   */
  list?: Array<Plan>
}
