/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CourseCertificate
 */
export interface CourseCertificate {
  /**
   *
   * @type {string}
   * @memberof CourseCertificate
   */
  authorName?: string
  /**
   *
   * @type {string}
   * @memberof CourseCertificate
   */
  courseName?: string
  /**
   *
   * @type {string}
   * @memberof CourseCertificate
   */
  date?: string
  /**
   *
   * @type {string}
   * @memberof CourseCertificate
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof CourseCertificate
   */
  url?: string
  /**
   *
   * @type {string}
   * @memberof CourseCertificate
   */
  userName?: string
}
