/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Achievement } from './achievement'
import { Journal } from './journal'

/**
 *
 * @export
 * @interface CreatedJournalWithCoins
 */
export interface CreatedJournalWithCoins {
  /**
   *
   * @type {Achievement}
   * @memberof CreatedJournalWithCoins
   */
  achievement?: Achievement
  /**
   *
   * @type {number}
   * @memberof CreatedJournalWithCoins
   */
  coinsEarnedThisTime?: number
  /**
   *
   * @type {number}
   * @memberof CreatedJournalWithCoins
   */
  currentCoinCount?: number
  /**
   *
   * @type {Journal}
   * @memberof CreatedJournalWithCoins
   */
  stored?: Journal
}
