/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface DailyLifeScoreData
 */
export interface DailyLifeScoreData {
  /**
   *
   * @type {number}
   * @memberof DailyLifeScoreData
   */
  avgScore?: number
  /**
   *
   * @type {string}
   * @memberof DailyLifeScoreData
   */
  clarity?: string
  /**
   *
   * @type {string}
   * @memberof DailyLifeScoreData
   */
  courage?: string
  /**
   *
   * @type {string}
   * @memberof DailyLifeScoreData
   */
  energy?: string
  /**
   *
   * @type {string}
   * @memberof DailyLifeScoreData
   */
  influence?: string
  /**
   *
   * @type {string}
   * @memberof DailyLifeScoreData
   */
  mood?: string
  /**
   *
   * @type {string}
   * @memberof DailyLifeScoreData
   */
  movement?: string
  /**
   *
   * @type {string}
   * @memberof DailyLifeScoreData
   */
  necessity?: string
  /**
   *
   * @type {string}
   * @memberof DailyLifeScoreData
   */
  nutrition?: string
  /**
   *
   * @type {string}
   * @memberof DailyLifeScoreData
   */
  organizationId?: string
  /**
   *
   * @type {string}
   * @memberof DailyLifeScoreData
   */
  organizationName?: string
  /**
   *
   * @type {string}
   * @memberof DailyLifeScoreData
   */
  productivity?: string
  /**
   *
   * @type {string}
   * @memberof DailyLifeScoreData
   */
  sleep?: string
  /**
   *
   * @type {number}
   * @memberof DailyLifeScoreData
   */
  submittedScoreCount?: number
  /**
   *
   * @type {string}
   * @memberof DailyLifeScoreData
   */
  time?: string
}
