/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TemporalUnit } from './temporal-unit'

/**
 *
 * @export
 * @interface Duration
 */
export interface Duration {
  /**
   *
   * @type {number}
   * @memberof Duration
   */
  nano?: number
  /**
   *
   * @type {boolean}
   * @memberof Duration
   */
  negative?: boolean
  /**
   *
   * @type {number}
   * @memberof Duration
   */
  seconds?: number
  /**
   *
   * @type {Array<TemporalUnit>}
   * @memberof Duration
   */
  units?: Array<TemporalUnit>
  /**
   *
   * @type {boolean}
   * @memberof Duration
   */
  zero?: boolean
}
