/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Decimal } from './decimal'

/**
 *
 * @export
 * @interface FacebookEvent
 */
export interface FacebookEvent {
  /**
   *
   * @type {string}
   * @memberof FacebookEvent
   */
  clickId?: string
  /**
   *
   * @type {string}
   * @memberof FacebookEvent
   */
  content_category?: string
  /**
   *
   * @type {Array<number>}
   * @memberof FacebookEvent
   */
  content_ids?: Array<number>
  /**
   *
   * @type {string}
   * @memberof FacebookEvent
   */
  content_name?: string
  /**
   *
   * @type {string}
   * @memberof FacebookEvent
   */
  content_type?: string
  /**
   *
   * @type {string}
   * @memberof FacebookEvent
   */
  currency?: string
  /**
   *
   * @type {string}
   * @memberof FacebookEvent
   */
  deDuplicationKey?: string
  /**
   *
   * @type {string}
   * @memberof FacebookEvent
   */
  eventName?: string
  /**
   *
   * @type {Decimal}
   * @memberof FacebookEvent
   */
  value?: Decimal
}
