/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GiftSubscription
 */
export interface GiftSubscription {
  /**
   *
   * @type {boolean}
   * @memberof GiftSubscription
   */
  buyerAutomaticTaxEnabled?: boolean
  /**
   *
   * @type {string}
   * @memberof GiftSubscription
   */
  buyerCountry?: string
  /**
   *
   * @type {string}
   * @memberof GiftSubscription
   */
  buyerEmail?: string
  /**
   *
   * @type {string}
   * @memberof GiftSubscription
   */
  buyerFirstName?: string
  /**
   *
   * @type {string}
   * @memberof GiftSubscription
   */
  buyerFullName?: string
  /**
   *
   * @type {string}
   * @memberof GiftSubscription
   */
  buyerPhoneNumber?: string
  /**
   *
   * @type {string}
   * @memberof GiftSubscription
   */
  buyerRegion?: string
  /**
   *
   * @type {string}
   * @memberof GiftSubscription
   */
  buyerZipCode?: string
  /**
   *
   * @type {string}
   * @memberof GiftSubscription
   */
  consumerEmail?: string
  /**
   *
   * @type {string}
   * @memberof GiftSubscription
   */
  consumerName?: string
  /**
   *
   * @type {number}
   * @memberof GiftSubscription
   */
  createTimestamp?: number
  /**
   *
   * @type {number}
   * @memberof GiftSubscription
   */
  deleteTimestamp?: number
  /**
   *
   * @type {string}
   * @memberof GiftSubscription
   */
  frequency?: GiftSubscriptionFrequencyEnum
  /**
   *
   * @type {string}
   * @memberof GiftSubscription
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof GiftSubscription
   */
  message?: string
  /**
   *
   * @type {boolean}
   * @memberof GiftSubscription
   */
  override?: boolean
  /**
   *
   * @type {string}
   * @memberof GiftSubscription
   */
  paymentMethodId?: string
  /**
   *
   * @type {string}
   * @memberof GiftSubscription
   */
  paymentSystem?: GiftSubscriptionPaymentSystemEnum
  /**
   *
   * @type {string}
   * @memberof GiftSubscription
   */
  stripeCustomerId?: string
  /**
   *
   * @type {string}
   * @memberof GiftSubscription
   */
  stripePriceId?: string
  /**
   *
   * @type {string}
   * @memberof GiftSubscription
   */
  stripeSubscriptionId?: string
  /**
   *
   * @type {boolean}
   * @memberof GiftSubscription
   */
  subscriptionCancelled?: boolean
  /**
   *
   * @type {number}
   * @memberof GiftSubscription
   */
  subscriptionExpiry?: number
  /**
   *
   * @type {string}
   * @memberof GiftSubscription
   */
  subscriptionLevel?: GiftSubscriptionSubscriptionLevelEnum
  /**
   *
   * @type {number}
   * @memberof GiftSubscription
   */
  updateTimestamp?: number
  /**
   *
   * @type {string}
   * @memberof GiftSubscription
   */
  uuid?: string
}

export const GiftSubscriptionFrequencyEnum = {
  Month: 'MONTH',
  Year: 'YEAR'
} as const

export type GiftSubscriptionFrequencyEnum =
  typeof GiftSubscriptionFrequencyEnum[keyof typeof GiftSubscriptionFrequencyEnum]
export const GiftSubscriptionPaymentSystemEnum = {
  Card: 'CARD',
  Paypal: 'PAYPAL',
  Apple: 'APPLE'
} as const

export type GiftSubscriptionPaymentSystemEnum =
  typeof GiftSubscriptionPaymentSystemEnum[keyof typeof GiftSubscriptionPaymentSystemEnum]
export const GiftSubscriptionSubscriptionLevelEnum = {
  Basic: 'BASIC',
  Growth: 'GROWTH',
  Mastery: 'MASTERY',
  Trial: 'TRIAL',
  None: 'NONE',
  Offer: 'OFFER',
  Challenge: 'CHALLENGE',
  Enterprise: 'ENTERPRISE',
  Allaccess: 'ALLACCESS'
} as const

export type GiftSubscriptionSubscriptionLevelEnum =
  typeof GiftSubscriptionSubscriptionLevelEnum[keyof typeof GiftSubscriptionSubscriptionLevelEnum]
