/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GiftSubscriptionUserDetail
 */
export interface GiftSubscriptionUserDetail {
  /**
   *
   * @type {string}
   * @memberof GiftSubscriptionUserDetail
   */
  email?: string
  /**
   *
   * @type {string}
   * @memberof GiftSubscriptionUserDetail
   */
  fullName?: string
  /**
   *
   * @type {string}
   * @memberof GiftSubscriptionUserDetail
   */
  stripePlanId?: string
}
