/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GiftSubscriptionRequestFormResponse
 */
export interface GiftSubscriptionRequestFormResponse {
  /**
   *
   * @type {string}
   * @memberof GiftSubscriptionRequestFormResponse
   */
  buyerEmail?: string
  /**
   *
   * @type {string}
   * @memberof GiftSubscriptionRequestFormResponse
   */
  buyerFullName?: string
  /**
   *
   * @type {{ [key: string]: string; }}
   * @memberof GiftSubscriptionRequestFormResponse
   */
  consumerEmails?: { [key: string]: string }
  /**
   *
   * @type {string}
   * @memberof GiftSubscriptionRequestFormResponse
   */
  message?: string
  /**
   *
   * @type {boolean}
   * @memberof GiftSubscriptionRequestFormResponse
   */
  paymentAbandonmentReminded?: boolean
  /**
   *
   * @type {number}
   * @memberof GiftSubscriptionRequestFormResponse
   */
  planId?: number
  /**
   *
   * @type {string}
   * @memberof GiftSubscriptionRequestFormResponse
   */
  token?: string
}
