/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GiftSubscriptionPurchaseRequest
 */
export interface GiftSubscriptionPurchaseRequest {
  /**
   *
   * @type {string}
   * @memberof GiftSubscriptionPurchaseRequest
   */
  buyerEmail?: string
  /**
   *
   * @type {string}
   * @memberof GiftSubscriptionPurchaseRequest
   */
  buyerFullName?: string
  /**
   *
   * @type {string}
   * @memberof GiftSubscriptionPurchaseRequest
   */
  buyerPhoneNumber?: string
  /**
   *
   * @type {{ [key: string]: string; }}
   * @memberof GiftSubscriptionPurchaseRequest
   */
  consumerEmails?: { [key: string]: string }
  /**
   *
   * @type {string}
   * @memberof GiftSubscriptionPurchaseRequest
   */
  country?: string
  /**
   *
   * @type {string}
   * @memberof GiftSubscriptionPurchaseRequest
   */
  deduplicationKey?: string
  /**
   *
   * @type {string}
   * @memberof GiftSubscriptionPurchaseRequest
   */
  message?: string
  /**
   *
   * @type {string}
   * @memberof GiftSubscriptionPurchaseRequest
   */
  region?: string
  /**
   *
   * @type {string}
   * @memberof GiftSubscriptionPurchaseRequest
   */
  stripePaymentMethodId?: string
  /**
   *
   * @type {string}
   * @memberof GiftSubscriptionPurchaseRequest
   */
  stripePlanId?: string
  /**
   *
   * @type {string}
   * @memberof GiftSubscriptionPurchaseRequest
   */
  zipCode?: string
}
