/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EmbeddedReminderRequest } from './embedded-reminder-request'
import { GoalMilestone } from './goal-milestone'
import { Plan1 } from './plan1'

/**
 *
 * @export
 * @interface GoalDto1
 */
export interface GoalDto1 {
  /**
   *
   * @type {boolean}
   * @memberof GoalDto1
   */
  complete?: boolean
  /**
   *
   * @type {string}
   * @memberof GoalDto1
   */
  description?: string
  /**
   *
   * @type {number}
   * @memberof GoalDto1
   */
  dueDate?: number
  /**
   *
   * @type {Array<string>}
   * @memberof GoalDto1
   */
  focusAreas?: Array<string>
  /**
   *
   * @type {Array<GoalMilestone>}
   * @memberof GoalDto1
   */
  goalMilestoneDtos?: Array<GoalMilestone>
  /**
   *
   * @type {string}
   * @memberof GoalDto1
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof GoalDto1
   */
  masterOptionalId?: string
  /**
   *
   * @type {string}
   * @memberof GoalDto1
   */
  masterPrimaryId?: string
  /**
   *
   * @type {string}
   * @memberof GoalDto1
   */
  masterSecondaryId?: string
  /**
   *
   * @type {number}
   * @memberof GoalDto1
   */
  order?: number
  /**
   *
   * @type {Array<string>}
   * @memberof GoalDto1
   */
  planIds?: Array<string>
  /**
   *
   * @type {Array<Plan1>}
   * @memberof GoalDto1
   */
  plans?: Array<Plan1>
  /**
   *
   * @type {EmbeddedReminderRequest}
   * @memberof GoalDto1
   */
  reminder?: EmbeddedReminderRequest
  /**
   *
   * @type {string}
   * @memberof GoalDto1
   */
  title?: string
  /**
   *
   * @type {string}
   * @memberof GoalDto1
   */
  type?: GoalDto1TypeEnum
}

export const GoalDto1TypeEnum = {
  Challenge: 'CHALLENGE',
  Journal: 'JOURNAL',
  Goal: 'GOAL',
  Plan: 'PLAN'
} as const

export type GoalDto1TypeEnum = typeof GoalDto1TypeEnum[keyof typeof GoalDto1TypeEnum]
