/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GoalMilestone
 */
export interface GoalMilestone {
  /**
   *
   * @type {boolean}
   * @memberof GoalMilestone
   */
  complete?: boolean
  /**
   *
   * @type {number}
   * @memberof GoalMilestone
   */
  completedTimestamp?: number
  /**
   *
   * @type {number}
   * @memberof GoalMilestone
   */
  createTimestamp?: number
  /**
   *
   * @type {number}
   * @memberof GoalMilestone
   */
  deleteTimestamp?: number
  /**
   *
   * @type {number}
   * @memberof GoalMilestone
   */
  dueDate?: number
  /**
   *
   * @type {string}
   * @memberof GoalMilestone
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof GoalMilestone
   */
  milestoneId?: string
  /**
   *
   * @type {string}
   * @memberof GoalMilestone
   */
  title?: string
  /**
   *
   * @type {number}
   * @memberof GoalMilestone
   */
  updateTimestamp?: number
}
