/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GrowthGroupInstance } from './growth-group-instance'

/**
 *
 * @export
 * @interface GrowthGroupInstanceResponse
 */
export interface GrowthGroupInstanceResponse {
  /**
   *
   * @type {number}
   * @memberof GrowthGroupInstanceResponse
   */
  count?: number
  /**
   *
   * @type {Array<GrowthGroupInstance>}
   * @memberof GrowthGroupInstanceResponse
   */
  growthGroupInstanceList?: Array<GrowthGroupInstance>
}
