/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GrowthGroupInstanceTime } from './growth-group-instance-time'

/**
 *
 * @export
 * @interface GrowthGroupUpdateRequest
 */
export interface GrowthGroupUpdateRequest {
  /**
   *
   * @type {string}
   * @memberof GrowthGroupUpdateRequest
   */
  agenda?: string
  /**
   *
   * @type {boolean}
   * @memberof GrowthGroupUpdateRequest
   */
  canGuestInvite?: boolean
  /**
   *
   * @type {string}
   * @memberof GrowthGroupUpdateRequest
   */
  date?: string
  /**
   *
   * @type {number}
   * @memberof GrowthGroupUpdateRequest
   */
  duration?: number
  /**
   *
   * @type {Array<GrowthGroupInstanceTime>}
   * @memberof GrowthGroupUpdateRequest
   */
  growthGroupInstanceTimes?: Array<GrowthGroupInstanceTime>
  /**
   *
   * @type {string}
   * @memberof GrowthGroupUpdateRequest
   */
  rrule?: string
  /**
   *
   * @type {string}
   * @memberof GrowthGroupUpdateRequest
   */
  slug?: string
  /**
   *
   * @type {string}
   * @memberof GrowthGroupUpdateRequest
   */
  time?: string
  /**
   *
   * @type {string}
   * @memberof GrowthGroupUpdateRequest
   */
  title?: string
  /**
   *
   * @type {string}
   * @memberof GrowthGroupUpdateRequest
   */
  type?: GrowthGroupUpdateRequestTypeEnum
}

export const GrowthGroupUpdateRequestTypeEnum = {
  Private: 'PRIVATE',
  Public: 'PUBLIC'
} as const

export type GrowthGroupUpdateRequestTypeEnum =
  typeof GrowthGroupUpdateRequestTypeEnum[keyof typeof GrowthGroupUpdateRequestTypeEnum]
