/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GrowthGroupInstanceUpdateRequest
 */
export interface GrowthGroupInstanceUpdateRequest {
  /**
   *
   * @type {string}
   * @memberof GrowthGroupInstanceUpdateRequest
   */
  agenda?: string
  /**
   *
   * @type {number}
   * @memberof GrowthGroupInstanceUpdateRequest
   */
  duration?: number
  /**
   *
   * @type {string}
   * @memberof GrowthGroupInstanceUpdateRequest
   */
  title?: string
}
