/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GrowthGroupUpcomingPackage
 */
export interface GrowthGroupUpcomingPackage {
  /**
   *
   * @type {number}
   * @memberof GrowthGroupUpcomingPackage
   */
  allowedLimit?: number
  /**
   *
   * @type {boolean}
   * @memberof GrowthGroupUpcomingPackage
   */
  cancelled?: boolean
  /**
   *
   * @type {number}
   * @memberof GrowthGroupUpcomingPackage
   */
  cancelledOn?: number
  /**
   *
   * @type {number}
   * @memberof GrowthGroupUpcomingPackage
   */
  consumed?: number
  /**
   *
   * @type {number}
   * @memberof GrowthGroupUpcomingPackage
   */
  createTimestamp?: number
  /**
   *
   * @type {number}
   * @memberof GrowthGroupUpcomingPackage
   */
  deleteTimestamp?: number
  /**
   *
   * @type {string}
   * @memberof GrowthGroupUpcomingPackage
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof GrowthGroupUpcomingPackage
   */
  licenseId?: string
  /**
   *
   * @type {string}
   * @memberof GrowthGroupUpcomingPackage
   */
  licenseType?: GrowthGroupUpcomingPackageLicenseTypeEnum
  /**
   *
   * @type {number}
   * @memberof GrowthGroupUpcomingPackage
   */
  packageEndTime?: number
  /**
   *
   * @type {number}
   * @memberof GrowthGroupUpcomingPackage
   */
  packagePrice?: number
  /**
   *
   * @type {number}
   * @memberof GrowthGroupUpcomingPackage
   */
  packageStartTime?: number
  /**
   *
   * @type {number}
   * @memberof GrowthGroupUpcomingPackage
   */
  participantsAllowed?: number
  /**
   *
   * @type {string}
   * @memberof GrowthGroupUpcomingPackage
   */
  paymentSystem?: GrowthGroupUpcomingPackagePaymentSystemEnum
  /**
   *
   * @type {string}
   * @memberof GrowthGroupUpcomingPackage
   */
  priceId?: string
  /**
   *
   * @type {string}
   * @memberof GrowthGroupUpcomingPackage
   */
  subscriptionId?: string
  /**
   *
   * @type {number}
   * @memberof GrowthGroupUpcomingPackage
   */
  updateTimestamp?: number
  /**
   *
   * @type {string}
   * @memberof GrowthGroupUpcomingPackage
   */
  userTimezone?: string
  /**
   *
   * @type {string}
   * @memberof GrowthGroupUpcomingPackage
   */
  uuid?: string
}

export const GrowthGroupUpcomingPackageLicenseTypeEnum = {
  ProSubscriptionPlan: 'PRO_SUBSCRIPTION_PLAN',
  ProTrialSubscriptionPlan: 'PRO_TRIAL_SUBSCRIPTION_PLAN',
  GgPackage: 'GG_PACKAGE'
} as const

export type GrowthGroupUpcomingPackageLicenseTypeEnum =
  typeof GrowthGroupUpcomingPackageLicenseTypeEnum[keyof typeof GrowthGroupUpcomingPackageLicenseTypeEnum]
export const GrowthGroupUpcomingPackagePaymentSystemEnum = {
  Card: 'CARD',
  Paypal: 'PAYPAL',
  Apple: 'APPLE'
} as const

export type GrowthGroupUpcomingPackagePaymentSystemEnum =
  typeof GrowthGroupUpcomingPackagePaymentSystemEnum[keyof typeof GrowthGroupUpcomingPackagePaymentSystemEnum]
