/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Hms } from './hms'

/**
 *
 * @export
 * @interface GrowthGroup
 */
export interface GrowthGroup {
  /**
   *
   * @type {boolean}
   * @memberof GrowthGroup
   */
  canGuestInvite?: boolean
  /**
   *
   * @type {string}
   * @memberof GrowthGroup
   */
  channel?: GrowthGroupChannelEnum
  /**
   *
   * @type {number}
   * @memberof GrowthGroup
   */
  createTimestamp?: number
  /**
   *
   * @type {string}
   * @memberof GrowthGroup
   */
  date?: string
  /**
   *
   * @type {number}
   * @memberof GrowthGroup
   */
  deleteTimestamp?: number
  /**
   *
   * @type {number}
   * @memberof GrowthGroup
   */
  duration?: number
  /**
   *
   * @type {Hms}
   * @memberof GrowthGroup
   */
  hms?: Hms
  /**
   *
   * @type {string}
   * @memberof GrowthGroup
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof GrowthGroup
   */
  rrule?: string
  /**
   *
   * @type {string}
   * @memberof GrowthGroup
   */
  slug?: string
  /**
   *
   * @type {string}
   * @memberof GrowthGroup
   */
  time?: string
  /**
   *
   * @type {string}
   * @memberof GrowthGroup
   */
  type?: GrowthGroupTypeEnum
  /**
   *
   * @type {number}
   * @memberof GrowthGroup
   */
  updateTimestamp?: number
  /**
   *
   * @type {string}
   * @memberof GrowthGroup
   */
  uuid?: string
}

export const GrowthGroupChannelEnum = {
  Audio: 'AUDIO',
  Video: 'VIDEO'
} as const

export type GrowthGroupChannelEnum = typeof GrowthGroupChannelEnum[keyof typeof GrowthGroupChannelEnum]
export const GrowthGroupTypeEnum = {
  Private: 'PRIVATE',
  Public: 'PUBLIC'
} as const

export type GrowthGroupTypeEnum = typeof GrowthGroupTypeEnum[keyof typeof GrowthGroupTypeEnum]
