/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Hms } from './hms'
import { ParticipantData } from './participant-data'

/**
 *
 * @export
 * @interface GrowthGroupInstance
 */
export interface GrowthGroupInstance {
  /**
   *
   * @type {number}
   * @memberof GrowthGroupInstance
   */
  actualEndTime?: number
  /**
   *
   * @type {number}
   * @memberof GrowthGroupInstance
   */
  actualStartTime?: number
  /**
   *
   * @type {string}
   * @memberof GrowthGroupInstance
   */
  agenda?: string
  /**
   *
   * @type {boolean}
   * @memberof GrowthGroupInstance
   */
  canGuestInvite?: boolean
  /**
   *
   * @type {boolean}
   * @memberof GrowthGroupInstance
   */
  cancelled?: boolean
  /**
   *
   * @type {string}
   * @memberof GrowthGroupInstance
   */
  channel?: GrowthGroupInstanceChannelEnum
  /**
   *
   * @type {number}
   * @memberof GrowthGroupInstance
   */
  createTimestamp?: number
  /**
   *
   * @type {string}
   * @memberof GrowthGroupInstance
   */
  date?: string
  /**
   *
   * @type {number}
   * @memberof GrowthGroupInstance
   */
  deleteTimestamp?: number
  /**
   *
   * @type {number}
   * @memberof GrowthGroupInstance
   */
  duration?: number
  /**
   *
   * @type {number}
   * @memberof GrowthGroupInstance
   */
  endTime?: number
  /**
   *
   * @type {string}
   * @memberof GrowthGroupInstance
   */
  groupId?: string
  /**
   *
   * @type {Hms}
   * @memberof GrowthGroupInstance
   */
  hms?: Hms
  /**
   *
   * @type {string}
   * @memberof GrowthGroupInstance
   */
  ianaTimezone?: string
  /**
   *
   * @type {string}
   * @memberof GrowthGroupInstance
   */
  id?: string
  /**
   *
   * @type {Array<ParticipantData>}
   * @memberof GrowthGroupInstance
   */
  participants?: Array<ParticipantData>
  /**
   *
   * @type {Array<string>}
   * @memberof GrowthGroupInstance
   */
  pinnedUuids?: Array<string>
  /**
   *
   * @type {string}
   * @memberof GrowthGroupInstance
   */
  reason?: GrowthGroupInstanceReasonEnum
  /**
   *
   * @type {string}
   * @memberof GrowthGroupInstance
   */
  rrule?: string
  /**
   *
   * @type {string}
   * @memberof GrowthGroupInstance
   */
  slug?: string
  /**
   *
   * @type {number}
   * @memberof GrowthGroupInstance
   */
  startTime?: number
  /**
   *
   * @type {string}
   * @memberof GrowthGroupInstance
   */
  state?: GrowthGroupInstanceStateEnum
  /**
   *
   * @type {string}
   * @memberof GrowthGroupInstance
   */
  time?: string
  /**
   *
   * @type {string}
   * @memberof GrowthGroupInstance
   */
  title?: string
  /**
   *
   * @type {string}
   * @memberof GrowthGroupInstance
   */
  type?: GrowthGroupInstanceTypeEnum
  /**
   *
   * @type {number}
   * @memberof GrowthGroupInstance
   */
  updateTimestamp?: number
  /**
   *
   * @type {string}
   * @memberof GrowthGroupInstance
   */
  uuid?: string
}

export const GrowthGroupInstanceChannelEnum = {
  Audio: 'AUDIO',
  Video: 'VIDEO'
} as const

export type GrowthGroupInstanceChannelEnum =
  typeof GrowthGroupInstanceChannelEnum[keyof typeof GrowthGroupInstanceChannelEnum]
export const GrowthGroupInstanceReasonEnum = {
  CancelledByHost: 'CANCELLED_BY_HOST',
  NotStartedOnTime: 'NOT_STARTED_ON_TIME',
  NotEnoughRsvp: 'NOT_ENOUGH_RSVP',
  SubscriptionCanceled: 'SUBSCRIPTION_CANCELED',
  DowngradeSubscription: 'DOWNGRADE_SUBSCRIPTION'
} as const

export type GrowthGroupInstanceReasonEnum =
  typeof GrowthGroupInstanceReasonEnum[keyof typeof GrowthGroupInstanceReasonEnum]
export const GrowthGroupInstanceStateEnum = {
  StartsInFuture: 'STARTS_IN_FUTURE',
  StartsSoon: 'STARTS_SOON',
  WaitingForHost: 'WAITING_FOR_HOST',
  Cancelled: 'CANCELLED',
  LiveNow: 'LIVE_NOW',
  Ended: 'ENDED'
} as const

export type GrowthGroupInstanceStateEnum =
  typeof GrowthGroupInstanceStateEnum[keyof typeof GrowthGroupInstanceStateEnum]
export const GrowthGroupInstanceTypeEnum = {
  Private: 'PRIVATE',
  Public: 'PUBLIC'
} as const

export type GrowthGroupInstanceTypeEnum = typeof GrowthGroupInstanceTypeEnum[keyof typeof GrowthGroupInstanceTypeEnum]
