/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GrowthGroupPackage
 */
export interface GrowthGroupPackage {
  /**
   *
   * @type {number}
   * @memberof GrowthGroupPackage
   */
  allowedLimit?: number
  /**
   *
   * @type {boolean}
   * @memberof GrowthGroupPackage
   */
  cancelled?: boolean
  /**
   *
   * @type {number}
   * @memberof GrowthGroupPackage
   */
  cancelledOn?: number
  /**
   *
   * @type {number}
   * @memberof GrowthGroupPackage
   */
  consumed?: number
  /**
   *
   * @type {number}
   * @memberof GrowthGroupPackage
   */
  createTimestamp?: number
  /**
   *
   * @type {number}
   * @memberof GrowthGroupPackage
   */
  deleteTimestamp?: number
  /**
   *
   * @type {string}
   * @memberof GrowthGroupPackage
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof GrowthGroupPackage
   */
  licenseId?: string
  /**
   *
   * @type {string}
   * @memberof GrowthGroupPackage
   */
  licenseType?: GrowthGroupPackageLicenseTypeEnum
  /**
   *
   * @type {number}
   * @memberof GrowthGroupPackage
   */
  packageEndTime?: number
  /**
   *
   * @type {number}
   * @memberof GrowthGroupPackage
   */
  packagePrice?: number
  /**
   *
   * @type {number}
   * @memberof GrowthGroupPackage
   */
  packageStartTime?: number
  /**
   *
   * @type {number}
   * @memberof GrowthGroupPackage
   */
  participantsAllowed?: number
  /**
   *
   * @type {string}
   * @memberof GrowthGroupPackage
   */
  paymentSystem?: GrowthGroupPackagePaymentSystemEnum
  /**
   *
   * @type {string}
   * @memberof GrowthGroupPackage
   */
  priceId?: string
  /**
   *
   * @type {string}
   * @memberof GrowthGroupPackage
   */
  subscriptionId?: string
  /**
   *
   * @type {number}
   * @memberof GrowthGroupPackage
   */
  updateTimestamp?: number
  /**
   *
   * @type {string}
   * @memberof GrowthGroupPackage
   */
  userTimezone?: string
  /**
   *
   * @type {string}
   * @memberof GrowthGroupPackage
   */
  uuid?: string
}

export const GrowthGroupPackageLicenseTypeEnum = {
  ProSubscriptionPlan: 'PRO_SUBSCRIPTION_PLAN',
  ProTrialSubscriptionPlan: 'PRO_TRIAL_SUBSCRIPTION_PLAN',
  GgPackage: 'GG_PACKAGE'
} as const

export type GrowthGroupPackageLicenseTypeEnum =
  typeof GrowthGroupPackageLicenseTypeEnum[keyof typeof GrowthGroupPackageLicenseTypeEnum]
export const GrowthGroupPackagePaymentSystemEnum = {
  Card: 'CARD',
  Paypal: 'PAYPAL',
  Apple: 'APPLE'
} as const

export type GrowthGroupPackagePaymentSystemEnum =
  typeof GrowthGroupPackagePaymentSystemEnum[keyof typeof GrowthGroupPackagePaymentSystemEnum]
