/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GrowthCoinTransactionByEvent } from './growth-coin-transaction-by-event'

/**
 *
 * @export
 * @interface GrowthCoinTransactionsGroupedByEvent
 */
export interface GrowthCoinTransactionsGroupedByEvent {
  /**
   *
   * @type {Array<GrowthCoinTransactionByEvent>}
   * @memberof GrowthCoinTransactionsGroupedByEvent
   */
  list?: Array<GrowthCoinTransactionByEvent>
  /**
   *
   * @type {number}
   * @memberof GrowthCoinTransactionsGroupedByEvent
   */
  totalCoins?: number
}
