/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GrowthGroupInstanceChat
 */
export interface GrowthGroupInstanceChat {
  /**
   *
   * @type {string}
   * @memberof GrowthGroupInstanceChat
   */
  chatId?: string
  /**
   *
   * @type {number}
   * @memberof GrowthGroupInstanceChat
   */
  createTimestamp?: number
  /**
   *
   * @type {number}
   * @memberof GrowthGroupInstanceChat
   */
  deleteTimestamp?: number
  /**
   *
   * @type {string}
   * @memberof GrowthGroupInstanceChat
   */
  groupId?: string
  /**
   *
   * @type {string}
   * @memberof GrowthGroupInstanceChat
   */
  groupInstanceId?: string
  /**
   *
   * @type {string}
   * @memberof GrowthGroupInstanceChat
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof GrowthGroupInstanceChat
   */
  message?: string
  /**
   *
   * @type {Array<string>}
   * @memberof GrowthGroupInstanceChat
   */
  recipientRoles?: Array<GrowthGroupInstanceChatRecipientRolesEnum>
  /**
   *
   * @type {string}
   * @memberof GrowthGroupInstanceChat
   */
  sender?: string
  /**
   *
   * @type {string}
   * @memberof GrowthGroupInstanceChat
   */
  senderName?: string
  /**
   *
   * @type {string}
   * @memberof GrowthGroupInstanceChat
   */
  senderRole?: GrowthGroupInstanceChatSenderRoleEnum
  /**
   *
   * @type {string}
   * @memberof GrowthGroupInstanceChat
   */
  time?: string
  /**
   *
   * @type {number}
   * @memberof GrowthGroupInstanceChat
   */
  updateTimestamp?: number
}

export const GrowthGroupInstanceChatRecipientRolesEnum = {
  Host: 'host',
  Attendee: 'attendee',
  CoHost: 'co-host',
  Speaker: 'speaker',
  WaitingRoom: 'waiting-room'
} as const

export type GrowthGroupInstanceChatRecipientRolesEnum =
  typeof GrowthGroupInstanceChatRecipientRolesEnum[keyof typeof GrowthGroupInstanceChatRecipientRolesEnum]
export const GrowthGroupInstanceChatSenderRoleEnum = {
  Host: 'host',
  Attendee: 'attendee',
  CoHost: 'co-host',
  Speaker: 'speaker',
  WaitingRoom: 'waiting-room'
} as const

export type GrowthGroupInstanceChatSenderRoleEnum =
  typeof GrowthGroupInstanceChatSenderRoleEnum[keyof typeof GrowthGroupInstanceChatSenderRoleEnum]
