/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GrowthGroupRemainingLicenseResponse
 */
export interface GrowthGroupRemainingLicenseResponse {
  /**
   *
   * @type {number}
   * @memberof GrowthGroupRemainingLicenseResponse
   */
  billingCycleEnd?: number
  /**
   *
   * @type {number}
   * @memberof GrowthGroupRemainingLicenseResponse
   */
  billingCycleStart?: number
  /**
   *
   * @type {number}
   * @memberof GrowthGroupRemainingLicenseResponse
   */
  participantsAllowed?: number
  /**
   *
   * @type {number}
   * @memberof GrowthGroupRemainingLicenseResponse
   */
  remainingLicenseCount?: number
}
