/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GrowthGroupInstanceTime
 */
export interface GrowthGroupInstanceTime {
  /**
   *
   * @type {number}
   * @memberof GrowthGroupInstanceTime
   */
  endTime?: number
  /**
   *
   * @type {number}
   * @memberof GrowthGroupInstanceTime
   */
  startTime?: number
}
