/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GrowthGroupInstanceTime } from './growth-group-instance-time'

/**
 *
 * @export
 * @interface GrowthGroupCreateRequest
 */
export interface GrowthGroupCreateRequest {
  /**
   *
   * @type {string}
   * @memberof GrowthGroupCreateRequest
   */
  agenda?: string
  /**
   *
   * @type {boolean}
   * @memberof GrowthGroupCreateRequest
   */
  canGuestInvite?: boolean
  /**
   *
   * @type {string}
   * @memberof GrowthGroupCreateRequest
   */
  channel?: GrowthGroupCreateRequestChannelEnum
  /**
   *
   * @type {string}
   * @memberof GrowthGroupCreateRequest
   */
  date?: string
  /**
   *
   * @type {number}
   * @memberof GrowthGroupCreateRequest
   */
  duration?: number
  /**
   *
   * @type {Array<GrowthGroupInstanceTime>}
   * @memberof GrowthGroupCreateRequest
   */
  growthGroupInstanceTimes?: Array<GrowthGroupInstanceTime>
  /**
   *
   * @type {string}
   * @memberof GrowthGroupCreateRequest
   */
  rrule?: string
  /**
   *
   * @type {string}
   * @memberof GrowthGroupCreateRequest
   */
  slug?: string
  /**
   *
   * @type {string}
   * @memberof GrowthGroupCreateRequest
   */
  time?: string
  /**
   *
   * @type {string}
   * @memberof GrowthGroupCreateRequest
   */
  title?: string
  /**
   *
   * @type {string}
   * @memberof GrowthGroupCreateRequest
   */
  type?: GrowthGroupCreateRequestTypeEnum
}

export const GrowthGroupCreateRequestChannelEnum = {
  Audio: 'AUDIO',
  Video: 'VIDEO'
} as const

export type GrowthGroupCreateRequestChannelEnum =
  typeof GrowthGroupCreateRequestChannelEnum[keyof typeof GrowthGroupCreateRequestChannelEnum]
export const GrowthGroupCreateRequestTypeEnum = {
  Private: 'PRIVATE',
  Public: 'PUBLIC'
} as const

export type GrowthGroupCreateRequestTypeEnum =
  typeof GrowthGroupCreateRequestTypeEnum[keyof typeof GrowthGroupCreateRequestTypeEnum]
