/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ParticipantData } from './participant-data'

/**
 *
 * @export
 * @interface GrowthGroupInstanceStatus
 */
export interface GrowthGroupInstanceStatus {
  /**
   *
   * @type {number}
   * @memberof GrowthGroupInstanceStatus
   */
  actualEndTime?: number
  /**
   *
   * @type {boolean}
   * @memberof GrowthGroupInstanceStatus
   */
  cancelled?: boolean
  /**
   *
   * @type {boolean}
   * @memberof GrowthGroupInstanceStatus
   */
  hasStarted?: boolean
  /**
   *
   * @type {number}
   * @memberof GrowthGroupInstanceStatus
   */
  joinCount?: number
  /**
   *
   * @type {number}
   * @memberof GrowthGroupInstanceStatus
   */
  joinLimit?: number
  /**
   *
   * @type {Array<ParticipantData>}
   * @memberof GrowthGroupInstanceStatus
   */
  participants?: Array<ParticipantData>
}
