/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GrowthGroupLicense } from './growth-group-license'
import { GrowthGroupPackage } from './growth-group-package'

/**
 *
 * @export
 * @interface GrowthGroupSubscriptionResponse
 */
export interface GrowthGroupSubscriptionResponse {
  /**
   *
   * @type {GrowthGroupLicense}
   * @memberof GrowthGroupSubscriptionResponse
   */
  growthGroupLicense?: GrowthGroupLicense
  /**
   *
   * @type {GrowthGroupPackage}
   * @memberof GrowthGroupSubscriptionResponse
   */
  growthGroupPackage?: GrowthGroupPackage
}
