/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface HpsCardResponse
 */
export interface HpsCardResponse {
  /**
   *
   * @type {boolean}
   * @memberof HpsCardResponse
   */
  highPerformanceHabitBuilderSeriesWatched?: boolean
  /**
   *
   * @type {boolean}
   * @memberof HpsCardResponse
   */
  highPerformanceHabitsDeluxeAudiobookListened?: boolean
  /**
   *
   * @type {boolean}
   * @memberof HpsCardResponse
   */
  lifeScoreAssessmentTaken?: boolean
  /**
   *
   * @type {boolean}
   * @memberof HpsCardResponse
   */
  sevenDayTransformationWeekWatched?: boolean
}
