/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { JournalResponse } from './journal-response'

/**
 *
 * @export
 * @interface JournalList
 */
export interface JournalList {
  /**
   *
   * @type {number}
   * @memberof JournalList
   */
  count?: number
  /**
   *
   * @type {Array<JournalResponse>}
   * @memberof JournalList
   */
  list?: Array<JournalResponse>
}
