/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface JournalEntryData
 */
export interface JournalEntryData {
  /**
   *
   * @type {number}
   * @memberof JournalEntryData
   */
  journalSubmittedCount?: number
  /**
   *
   * @type {string}
   * @memberof JournalEntryData
   */
  organizationId?: string
  /**
   *
   * @type {string}
   * @memberof JournalEntryData
   */
  organizationName?: string
  /**
   *
   * @type {string}
   * @memberof JournalEntryData
   */
  time?: string
}
