/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ObjectId } from './object-id'
import { Prompt } from './prompt'

/**
 *
 * @export
 * @interface JournalResponse
 */
export interface JournalResponse {
  /**
   *
   * @type {ObjectId}
   * @memberof JournalResponse
   */
  _id?: ObjectId
  /**
   *
   * @type {string}
   * @memberof JournalResponse
   */
  category?: string
  /**
   *
   * @type {number}
   * @memberof JournalResponse
   */
  createTimestamp?: number
  /**
   *
   * @type {object}
   * @memberof JournalResponse
   */
  data?: object
  /**
   *
   * @type {boolean}
   * @memberof JournalResponse
   */
  encrypted?: boolean
  /**
   *
   * @type {string}
   * @memberof JournalResponse
   */
  id?: string
  /**
   *
   * @type {boolean}
   * @memberof JournalResponse
   */
  linked?: boolean
  /**
   *
   * @type {boolean}
   * @memberof JournalResponse
   */
  masterLink?: boolean
  /**
   *
   * @type {{ [key: string]: string; }}
   * @memberof JournalResponse
   */
  photosIds?: { [key: string]: string }
  /**
   *
   * @type {Prompt}
   * @memberof JournalResponse
   */
  prompt?: Prompt
  /**
   *
   * @type {number}
   * @memberof JournalResponse
   */
  updateTimestamp?: number
  /**
   *
   * @type {string}
   * @memberof JournalResponse
   */
  uuid?: string
}
