/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface KajabiWebhookPayload
 */
export interface KajabiWebhookPayload {
  /**
   *
   * @type {string}
   * @memberof KajabiWebhookPayload
   */
  contact_phone_number?: string
  /**
   *
   * @type {boolean}
   * @memberof KajabiWebhookPayload
   */
  trial?: boolean
  /**
   *
   * @type {number}
   * @memberof KajabiWebhookPayload
   */
  offer_id?: number
  /**
   *
   * @type {string}
   * @memberof KajabiWebhookPayload
   */
  offer_title?: string
  /**
   *
   * @type {string}
   * @memberof KajabiWebhookPayload
   */
  offer_reference?: string
  /**
   *
   * @type {boolean}
   * @memberof KajabiWebhookPayload
   */
  opt_in?: boolean
  /**
   *
   * @type {number}
   * @memberof KajabiWebhookPayload
   */
  member_id?: number
  /**
   *
   * @type {string}
   * @memberof KajabiWebhookPayload
   */
  member_email?: string
  /**
   *
   * @type {string}
   * @memberof KajabiWebhookPayload
   */
  member_name?: string
  /**
   *
   * @type {string}
   * @memberof KajabiWebhookPayload
   */
  member_first_name?: string
  /**
   *
   * @type {string}
   * @memberof KajabiWebhookPayload
   */
  member_last_name?: string
}
