/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KajabiWebhookPayload } from './kajabi-webhook-payload'

/**
 *
 * @export
 * @interface KajabiWebhookRequest
 */
export interface KajabiWebhookRequest {
  /**
   *
   * @type {string}
   * @memberof KajabiWebhookRequest
   */
  event?: string
  /**
   *
   * @type {string}
   * @memberof KajabiWebhookRequest
   */
  id?: string
  /**
   *
   * @type {KajabiWebhookPayload}
   * @memberof KajabiWebhookRequest
   */
  payload?: KajabiWebhookPayload
}
