/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface LatestReceiptInfo
 */
export interface LatestReceiptInfo {
  /**
   *
   * @type {string}
   * @memberof LatestReceiptInfo
   */
  expires_date?: string
  /**
   *
   * @type {string}
   * @memberof LatestReceiptInfo
   */
  expires_date_ms?: string
  /**
   *
   * @type {string}
   * @memberof LatestReceiptInfo
   */
  expires_date_pst?: string
  /**
   *
   * @type {string}
   * @memberof LatestReceiptInfo
   */
  is_in_intro_offer_period?: string
  /**
   *
   * @type {string}
   * @memberof LatestReceiptInfo
   */
  is_trial_period?: string
  /**
   *
   * @type {string}
   * @memberof LatestReceiptInfo
   */
  original_purchase_date?: string
  /**
   *
   * @type {string}
   * @memberof LatestReceiptInfo
   */
  original_purchase_date_ms?: string
  /**
   *
   * @type {string}
   * @memberof LatestReceiptInfo
   */
  original_purchase_date_pst?: string
  /**
   *
   * @type {string}
   * @memberof LatestReceiptInfo
   */
  original_transaction_id?: string
  /**
   *
   * @type {string}
   * @memberof LatestReceiptInfo
   */
  product_id?: string
  /**
   *
   * @type {string}
   * @memberof LatestReceiptInfo
   */
  purchase_date?: string
  /**
   *
   * @type {string}
   * @memberof LatestReceiptInfo
   */
  purchase_date_ms?: string
  /**
   *
   * @type {string}
   * @memberof LatestReceiptInfo
   */
  purchase_date_pst?: string
  /**
   *
   * @type {string}
   * @memberof LatestReceiptInfo
   */
  quantity?: string
  /**
   *
   * @type {string}
   * @memberof LatestReceiptInfo
   */
  subscription_group_identifier?: string
  /**
   *
   * @type {string}
   * @memberof LatestReceiptInfo
   */
  transaction_id?: string
  /**
   *
   * @type {string}
   * @memberof LatestReceiptInfo
   */
  web_order_line_item_id?: string
}
