/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Lead
 */
export interface Lead {
  /**
   *
   * @type {string}
   * @memberof Lead
   */
  email?: string
  /**
   *
   * @type {number}
   * @memberof Lead
   */
  id?: number
  /**
   *
   * @type {string}
   * @memberof Lead
   */
  state?: string
}
