/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LessonComment } from './lesson-comment'

/**
 *
 * @export
 * @interface LessonCommentList
 */
export interface LessonCommentList {
  /**
   *
   * @type {Array<LessonComment>}
   * @memberof LessonCommentList
   */
  list?: Array<LessonComment>
  /**
   *
   * @type {number}
   * @memberof LessonCommentList
   */
  total?: number
}
