/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface LessonComment
 */
export interface LessonComment {
  /**
   *
   * @type {number}
   * @memberof LessonComment
   */
  courseId?: number
  /**
   *
   * @type {number}
   * @memberof LessonComment
   */
  createTimestamp?: number
  /**
   *
   * @type {string}
   * @memberof LessonComment
   */
  data?: string
  /**
   *
   * @type {number}
   * @memberof LessonComment
   */
  deleteTimestamp?: number
  /**
   *
   * @type {string}
   * @memberof LessonComment
   */
  id?: string
  /**
   *
   * @type {number}
   * @memberof LessonComment
   */
  lesson?: number
  /**
   *
   * @type {string}
   * @memberof LessonComment
   */
  profileURL?: string
  /**
   *
   * @type {number}
   * @memberof LessonComment
   */
  updateTimestamp?: number
  /**
   *
   * @type {string}
   * @memberof LessonComment
   */
  username?: string
  /**
   *
   * @type {string}
   * @memberof LessonComment
   */
  uuid?: string
}
