/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface LessonNoteRequest
 */
export interface LessonNoteRequest {
  /**
   *
   * @type {number}
   * @memberof LessonNoteRequest
   */
  courseId?: number
  /**
   *
   * @type {number}
   * @memberof LessonNoteRequest
   */
  lessonId?: number
  /**
   *
   * @type {string}
   * @memberof LessonNoteRequest
   */
  noteContent?: string
  /**
   *
   * @type {string}
   * @memberof LessonNoteRequest
   */
  noteId?: string
  /**
   *
   * @type {number}
   * @memberof LessonNoteRequest
   */
  timeCode?: number
  /**
   *
   * @type {number}
   * @memberof LessonNoteRequest
   */
  videoTs?: number
}
