/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface LifeScoreChartData
 */
export interface LifeScoreChartData {
  /**
   *
   * @type {string}
   * @memberof LifeScoreChartData
   */
  dayDateString?: string
  /**
   *
   * @type {string}
   * @memberof LifeScoreChartData
   */
  monthEndDateString?: string
  /**
   *
   * @type {string}
   * @memberof LifeScoreChartData
   */
  monthStartDateString?: string
  /**
   *
   * @type {number}
   * @memberof LifeScoreChartData
   */
  score?: number
  /**
   *
   * @type {string}
   * @memberof LifeScoreChartData
   */
  weekEndDateString?: string
  /**
   *
   * @type {string}
   * @memberof LifeScoreChartData
   */
  weekStartDateString?: string
}
