/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LiveEventComment } from './live-event-comment'

/**
 *
 * @export
 * @interface ListResponseLiveEventComment
 */
export interface ListResponseLiveEventComment {
  /**
   *
   * @type {Array<LiveEventComment>}
   * @memberof ListResponseLiveEventComment
   */
  list?: Array<LiveEventComment>
  /**
   *
   * @type {number}
   * @memberof ListResponseLiveEventComment
   */
  total?: number
}
