/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface LoginResponse
 */
export interface LoginResponse {
  /**
   *
   * @type {string}
   * @memberof LoginResponse
   */
  authenticationToken?: string
  /**
   *
   * @type {string}
   * @memberof LoginResponse
   */
  errorMessage?: string
  /**
   *
   * @type {boolean}
   * @memberof LoginResponse
   */
  isSuccess?: boolean
  /**
   *
   * @type {string}
   * @memberof LoginResponse
   */
  tribeRedirectUrl?: string
  /**
   *
   * @type {string}
   * @memberof LoginResponse
   */
  tribeToken?: string
}
