/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface MarketingValidationResponse
 */
export interface MarketingValidationResponse {
  /**
   *
   * @type {boolean}
   * @memberof MarketingValidationResponse
   */
  error?: boolean
  /**
   *
   * @type {string}
   * @memberof MarketingValidationResponse
   */
  reason?: string
  /**
   *
   * @type {boolean}
   * @memberof MarketingValidationResponse
   */
  userExists?: boolean
}
