/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface MarketingRegistrationValidationRequest
 */
export interface MarketingRegistrationValidationRequest {
  /**
   *
   * @type {number}
   * @memberof MarketingRegistrationValidationRequest
   */
  campaignId?: number
  /**
   *
   * @type {string}
   * @memberof MarketingRegistrationValidationRequest
   */
  campaignType?: MarketingRegistrationValidationRequestCampaignTypeEnum
  /**
   *
   * @type {string}
   * @memberof MarketingRegistrationValidationRequest
   */
  email?: string
}

export const MarketingRegistrationValidationRequestCampaignTypeEnum = {
  LiveEvent: 'LIVE_EVENT',
  Challenge: 'CHALLENGE',
  Plan: 'PLAN',
  Offer: 'OFFER'
} as const

export type MarketingRegistrationValidationRequestCampaignTypeEnum =
  typeof MarketingRegistrationValidationRequestCampaignTypeEnum[keyof typeof MarketingRegistrationValidationRequestCampaignTypeEnum]
