/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { View } from './view'

/**
 *
 * @export
 * @interface ModelAndView
 */
export interface ModelAndView {
  /**
   *
   * @type {boolean}
   * @memberof ModelAndView
   */
  empty?: boolean
  /**
   *
   * @type {object}
   * @memberof ModelAndView
   */
  model?: object
  /**
   *
   * @type {{ [key: string]: object; }}
   * @memberof ModelAndView
   */
  modelMap?: { [key: string]: object }
  /**
   *
   * @type {boolean}
   * @memberof ModelAndView
   */
  reference?: boolean
  /**
   *
   * @type {string}
   * @memberof ModelAndView
   */
  status?: ModelAndViewStatusEnum
  /**
   *
   * @type {View}
   * @memberof ModelAndView
   */
  view?: View
  /**
   *
   * @type {string}
   * @memberof ModelAndView
   */
  viewName?: string
}

export const ModelAndViewStatusEnum = {
  Continue: 'CONTINUE',
  SwitchingProtocols: 'SWITCHING_PROTOCOLS',
  Processing: 'PROCESSING',
  Checkpoint: 'CHECKPOINT',
  Ok: 'OK',
  Created: 'CREATED',
  Accepted: 'ACCEPTED',
  NonAuthoritativeInformation: 'NON_AUTHORITATIVE_INFORMATION',
  NoContent: 'NO_CONTENT',
  ResetContent: 'RESET_CONTENT',
  PartialContent: 'PARTIAL_CONTENT',
  MultiStatus: 'MULTI_STATUS',
  AlreadyReported: 'ALREADY_REPORTED',
  ImUsed: 'IM_USED',
  MultipleChoices: 'MULTIPLE_CHOICES',
  MovedPermanently: 'MOVED_PERMANENTLY',
  Found: 'FOUND',
  MovedTemporarily: 'MOVED_TEMPORARILY',
  SeeOther: 'SEE_OTHER',
  NotModified: 'NOT_MODIFIED',
  UseProxy: 'USE_PROXY',
  TemporaryRedirect: 'TEMPORARY_REDIRECT',
  PermanentRedirect: 'PERMANENT_REDIRECT',
  BadRequest: 'BAD_REQUEST',
  Unauthorized: 'UNAUTHORIZED',
  PaymentRequired: 'PAYMENT_REQUIRED',
  Forbidden: 'FORBIDDEN',
  NotFound: 'NOT_FOUND',
  MethodNotAllowed: 'METHOD_NOT_ALLOWED',
  NotAcceptable: 'NOT_ACCEPTABLE',
  ProxyAuthenticationRequired: 'PROXY_AUTHENTICATION_REQUIRED',
  RequestTimeout: 'REQUEST_TIMEOUT',
  Conflict: 'CONFLICT',
  Gone: 'GONE',
  LengthRequired: 'LENGTH_REQUIRED',
  PreconditionFailed: 'PRECONDITION_FAILED',
  PayloadTooLarge: 'PAYLOAD_TOO_LARGE',
  RequestEntityTooLarge: 'REQUEST_ENTITY_TOO_LARGE',
  UriTooLong: 'URI_TOO_LONG',
  RequestUriTooLong: 'REQUEST_URI_TOO_LONG',
  UnsupportedMediaType: 'UNSUPPORTED_MEDIA_TYPE',
  RequestedRangeNotSatisfiable: 'REQUESTED_RANGE_NOT_SATISFIABLE',
  ExpectationFailed: 'EXPECTATION_FAILED',
  IAmATeapot: 'I_AM_A_TEAPOT',
  InsufficientSpaceOnResource: 'INSUFFICIENT_SPACE_ON_RESOURCE',
  MethodFailure: 'METHOD_FAILURE',
  DestinationLocked: 'DESTINATION_LOCKED',
  UnprocessableEntity: 'UNPROCESSABLE_ENTITY',
  Locked: 'LOCKED',
  FailedDependency: 'FAILED_DEPENDENCY',
  TooEarly: 'TOO_EARLY',
  UpgradeRequired: 'UPGRADE_REQUIRED',
  PreconditionRequired: 'PRECONDITION_REQUIRED',
  TooManyRequests: 'TOO_MANY_REQUESTS',
  RequestHeaderFieldsTooLarge: 'REQUEST_HEADER_FIELDS_TOO_LARGE',
  UnavailableForLegalReasons: 'UNAVAILABLE_FOR_LEGAL_REASONS',
  InternalServerError: 'INTERNAL_SERVER_ERROR',
  NotImplemented: 'NOT_IMPLEMENTED',
  BadGateway: 'BAD_GATEWAY',
  ServiceUnavailable: 'SERVICE_UNAVAILABLE',
  GatewayTimeout: 'GATEWAY_TIMEOUT',
  HttpVersionNotSupported: 'HTTP_VERSION_NOT_SUPPORTED',
  VariantAlsoNegotiates: 'VARIANT_ALSO_NEGOTIATES',
  InsufficientStorage: 'INSUFFICIENT_STORAGE',
  LoopDetected: 'LOOP_DETECTED',
  BandwidthLimitExceeded: 'BANDWIDTH_LIMIT_EXCEEDED',
  NotExtended: 'NOT_EXTENDED',
  NetworkAuthenticationRequired: 'NETWORK_AUTHENTICATION_REQUIRED'
} as const

export type ModelAndViewStatusEnum = typeof ModelAndViewStatusEnum[keyof typeof ModelAndViewStatusEnum]
