/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface MonthlyLifeScoreData
 */
export interface MonthlyLifeScoreData {
  /**
   *
   * @type {number}
   * @memberof MonthlyLifeScoreData
   */
  avgScore?: number
  /**
   *
   * @type {string}
   * @memberof MonthlyLifeScoreData
   */
  experiences?: string
  /**
   *
   * @type {string}
   * @memberof MonthlyLifeScoreData
   */
  family?: string
  /**
   *
   * @type {string}
   * @memberof MonthlyLifeScoreData
   */
  finances?: string
  /**
   *
   * @type {string}
   * @memberof MonthlyLifeScoreData
   */
  friends?: string
  /**
   *
   * @type {string}
   * @memberof MonthlyLifeScoreData
   */
  health?: string
  /**
   *
   * @type {string}
   * @memberof MonthlyLifeScoreData
   */
  learning?: string
  /**
   *
   * @type {string}
   * @memberof MonthlyLifeScoreData
   */
  mental?: string
  /**
   *
   * @type {string}
   * @memberof MonthlyLifeScoreData
   */
  mission?: string
  /**
   *
   * @type {string}
   * @memberof MonthlyLifeScoreData
   */
  organizationId?: string
  /**
   *
   * @type {string}
   * @memberof MonthlyLifeScoreData
   */
  organizationName?: string
  /**
   *
   * @type {string}
   * @memberof MonthlyLifeScoreData
   */
  partner?: string
  /**
   *
   * @type {string}
   * @memberof MonthlyLifeScoreData
   */
  spirit?: string
  /**
   *
   * @type {number}
   * @memberof MonthlyLifeScoreData
   */
  submittedScoreCount?: number
  /**
   *
   * @type {string}
   * @memberof MonthlyLifeScoreData
   */
  time?: string
}
