/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface NotificationPreference
 */
export interface NotificationPreference {
  /**
   *
   * @type {number}
   * @memberof NotificationPreference
   */
  createTimestamp?: number
  /**
   *
   * @type {number}
   * @memberof NotificationPreference
   */
  deleteTimestamp?: number
  /**
   *
   * @type {boolean}
   * @memberof NotificationPreference
   */
  emailGrowthDayNews?: boolean
  /**
   *
   * @type {boolean}
   * @memberof NotificationPreference
   */
  emailLiveEvent?: boolean
  /**
   *
   * @type {boolean}
   * @memberof NotificationPreference
   */
  emailSundayNote?: boolean
  /**
   *
   * @type {boolean}
   * @memberof NotificationPreference
   */
  emailWeeklyGrowthReport?: boolean
  /**
   *
   * @type {string}
   * @memberof NotificationPreference
   */
  id?: string
  /**
   *
   * @type {boolean}
   * @memberof NotificationPreference
   */
  inAppChallengeAndPlan?: boolean
  /**
   *
   * @type {boolean}
   * @memberof NotificationPreference
   */
  inAppGoalAndMilestone?: boolean
  /**
   *
   * @type {boolean}
   * @memberof NotificationPreference
   */
  inAppLiveEvent?: boolean
  /**
   *
   * @type {boolean}
   * @memberof NotificationPreference
   */
  inAppPersonalPrompt?: boolean
  /**
   *
   * @type {boolean}
   * @memberof NotificationPreference
   */
  pushChallenges?: boolean
  /**
   *
   * @type {boolean}
   * @memberof NotificationPreference
   */
  pushGrowthGroups?: boolean
  /**
   *
   * @type {boolean}
   * @memberof NotificationPreference
   */
  pushLiveEvents?: boolean
  /**
   *
   * @type {boolean}
   * @memberof NotificationPreference
   */
  pushReminder?: boolean
  /**
   *
   * @type {number}
   * @memberof NotificationPreference
   */
  updateTimestamp?: number
  /**
   *
   * @type {string}
   * @memberof NotificationPreference
   */
  uuid?: string
}
