/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ObjectId
 */
export interface ObjectId {
  /**
   *
   * @type {number}
   * @memberof ObjectId
   */
  counter?: number
  /**
   *
   * @type {string}
   * @memberof ObjectId
   */
  date?: string
  /**
   *
   * @type {number}
   * @memberof ObjectId
   */
  machineIdentifier?: number
  /**
   *
   * @type {number}
   * @memberof ObjectId
   */
  processIdentifier?: number
  /**
   *
   * @type {number}
   * @memberof ObjectId
   */
  time?: number
  /**
   *
   * @type {number}
   * @memberof ObjectId
   */
  timeSecond?: number
  /**
   *
   * @type {number}
   * @memberof ObjectId
   */
  timestamp?: number
}
