/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface OrganizationResponse
 */
export interface OrganizationResponse {
  /**
   *
   * @type {string}
   * @memberof OrganizationResponse
   */
  country?: string
  /**
   *
   * @type {string}
   * @memberof OrganizationResponse
   */
  invitationVideoUrl?: string
  /**
   *
   * @type {string}
   * @memberof OrganizationResponse
   */
  logoUrl?: string
  /**
   *
   * @type {string}
   * @memberof OrganizationResponse
   */
  name?: string
  /**
   *
   * @type {string}
   * @memberof OrganizationResponse
   */
  organizationId?: string
  /**
   *
   * @type {string}
   * @memberof OrganizationResponse
   */
  organizationSubscribeLink?: string
  /**
   *
   * @type {string}
   * @memberof OrganizationResponse
   */
  paymentFlow?: OrganizationResponsePaymentFlowEnum
  /**
   *
   * @type {string}
   * @memberof OrganizationResponse
   */
  plan?: OrganizationResponsePlanEnum
  /**
   *
   * @type {string}
   * @memberof OrganizationResponse
   */
  planFrequency?: OrganizationResponsePlanFrequencyEnum
  /**
   *
   * @type {string}
   * @memberof OrganizationResponse
   */
  planName?: string
  /**
   *
   * @type {string}
   * @memberof OrganizationResponse
   */
  region?: string
  /**
   *
   * @type {boolean}
   * @memberof OrganizationResponse
   */
  subscriptionCancelled?: boolean
  /**
   *
   * @type {string}
   * @memberof OrganizationResponse
   */
  subscriptionLinkVisibility?: OrganizationResponseSubscriptionLinkVisibilityEnum
  /**
   *
   * @type {string}
   * @memberof OrganizationResponse
   */
  zipCode?: string
}

export const OrganizationResponsePaymentFlowEnum = {
  Organization: 'ORGANIZATION',
  Employee: 'EMPLOYEE'
} as const

export type OrganizationResponsePaymentFlowEnum =
  typeof OrganizationResponsePaymentFlowEnum[keyof typeof OrganizationResponsePaymentFlowEnum]
export const OrganizationResponsePlanEnum = {
  Basic: 'BASIC',
  Growth: 'GROWTH',
  Mastery: 'MASTERY',
  Trial: 'TRIAL',
  None: 'NONE',
  Offer: 'OFFER',
  Challenge: 'CHALLENGE',
  Enterprise: 'ENTERPRISE'
} as const

export type OrganizationResponsePlanEnum =
  typeof OrganizationResponsePlanEnum[keyof typeof OrganizationResponsePlanEnum]
export const OrganizationResponsePlanFrequencyEnum = {
  Month: 'MONTH',
  Year: 'YEAR'
} as const

export type OrganizationResponsePlanFrequencyEnum =
  typeof OrganizationResponsePlanFrequencyEnum[keyof typeof OrganizationResponsePlanFrequencyEnum]
export const OrganizationResponseSubscriptionLinkVisibilityEnum = {
  Public: 'PUBLIC',
  Private: 'PRIVATE'
} as const

export type OrganizationResponseSubscriptionLinkVisibilityEnum =
  typeof OrganizationResponseSubscriptionLinkVisibilityEnum[keyof typeof OrganizationResponseSubscriptionLinkVisibilityEnum]
