/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface OrganizationUserResponse
 */
export interface OrganizationUserResponse {
  /**
   *
   * @type {number}
   * @memberof OrganizationUserResponse
   */
  createTimestamp?: number
  /**
   *
   * @type {boolean}
   * @memberof OrganizationUserResponse
   */
  deactivated?: boolean
  /**
   *
   * @type {number}
   * @memberof OrganizationUserResponse
   */
  deactivatedOn?: number
  /**
   *
   * @type {number}
   * @memberof OrganizationUserResponse
   */
  deleteTimestamp?: number
  /**
   *
   * @type {boolean}
   * @memberof OrganizationUserResponse
   */
  deleted?: boolean
  /**
   *
   * @type {string}
   * @memberof OrganizationUserResponse
   */
  departmentId?: string
  /**
   *
   * @type {string}
   * @memberof OrganizationUserResponse
   */
  email?: string
  /**
   *
   * @type {string}
   * @memberof OrganizationUserResponse
   */
  id?: string
  /**
   *
   * @type {boolean}
   * @memberof OrganizationUserResponse
   */
  invitationAccepted?: boolean
  /**
   *
   * @type {number}
   * @memberof OrganizationUserResponse
   */
  invitationAcceptedOn?: number
  /**
   *
   * @type {number}
   * @memberof OrganizationUserResponse
   */
  invitationSentOn?: number
  /**
   *
   * @type {string}
   * @memberof OrganizationUserResponse
   */
  name?: string
  /**
   *
   * @type {string}
   * @memberof OrganizationUserResponse
   */
  organizationId?: string
  /**
   *
   * @type {number}
   * @memberof OrganizationUserResponse
   */
  roleId?: number
  /**
   *
   * @type {string}
   * @memberof OrganizationUserResponse
   */
  roleName?: string
  /**
   *
   * @type {number}
   * @memberof OrganizationUserResponse
   */
  updateTimestamp?: number
  /**
   *
   * @type {string}
   * @memberof OrganizationUserResponse
   */
  uuid?: string
}
