/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Organization
 */
export interface Organization {
  /**
   *
   * @type {boolean}
   * @memberof Organization
   */
  automaticTaxEnabled?: boolean
  /**
   *
   * @type {string}
   * @memberof Organization
   */
  country?: string
  /**
   *
   * @type {number}
   * @memberof Organization
   */
  createTimestamp?: number
  /**
   *
   * @type {boolean}
   * @memberof Organization
   */
  dataCompliancePolicyAccepted?: boolean
  /**
   *
   * @type {number}
   * @memberof Organization
   */
  deleteTimestamp?: number
  /**
   *
   * @type {string}
   * @memberof Organization
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof Organization
   */
  invitationVideoUrl?: string
  /**
   *
   * @type {string}
   * @memberof Organization
   */
  logoUrl?: string
  /**
   *
   * @type {string}
   * @memberof Organization
   */
  name?: string
  /**
   *
   * @type {string}
   * @memberof Organization
   */
  organizationSubscribeLink?: string
  /**
   *
   * @type {string}
   * @memberof Organization
   */
  paymentMethodExpiry?: string
  /**
   *
   * @type {string}
   * @memberof Organization
   */
  paymentMethodLastFour?: string
  /**
   *
   * @type {string}
   * @memberof Organization
   */
  paymentMethodType?: OrganizationPaymentMethodTypeEnum
  /**
   *
   * @type {string}
   * @memberof Organization
   */
  paymentMethodVendor?: string
  /**
   *
   * @type {string}
   * @memberof Organization
   */
  phoneNumber?: string
  /**
   *
   * @type {string}
   * @memberof Organization
   */
  plan?: OrganizationPlanEnum
  /**
   *
   * @type {string}
   * @memberof Organization
   */
  planFrequency?: OrganizationPlanFrequencyEnum
  /**
   *
   * @type {string}
   * @memberof Organization
   */
  planName?: string
  /**
   *
   * @type {string}
   * @memberof Organization
   */
  region?: string
  /**
   *
   * @type {number}
   * @memberof Organization
   */
  seats?: number
  /**
   *
   * @type {string}
   * @memberof Organization
   */
  stripeCustomerId?: string
  /**
   *
   * @type {string}
   * @memberof Organization
   */
  stripePaymentMethodId?: string
  /**
   *
   * @type {string}
   * @memberof Organization
   */
  stripePriceId?: string
  /**
   *
   * @type {string}
   * @memberof Organization
   */
  stripeSubscriptionId?: string
  /**
   *
   * @type {number}
   * @memberof Organization
   */
  subscriptionAmount?: number
  /**
   *
   * @type {boolean}
   * @memberof Organization
   */
  subscriptionCancelled?: boolean
  /**
   *
   * @type {number}
   * @memberof Organization
   */
  subscriptionEndDate?: number
  /**
   *
   * @type {number}
   * @memberof Organization
   */
  subscriptionStartDate?: number
  /**
   *
   * @type {boolean}
   * @memberof Organization
   */
  teamAssessmentEnabled?: boolean
  /**
   *
   * @type {number}
   * @memberof Organization
   */
  updateTimestamp?: number
  /**
   *
   * @type {string}
   * @memberof Organization
   */
  zipCode?: string
}

export const OrganizationPaymentMethodTypeEnum = {
  Card: 'CARD',
  Paypal: 'PAYPAL',
  Apple: 'APPLE'
} as const

export type OrganizationPaymentMethodTypeEnum =
  typeof OrganizationPaymentMethodTypeEnum[keyof typeof OrganizationPaymentMethodTypeEnum]
export const OrganizationPlanEnum = {
  Basic: 'BASIC',
  Growth: 'GROWTH',
  Mastery: 'MASTERY',
  Trial: 'TRIAL',
  None: 'NONE',
  Offer: 'OFFER',
  Challenge: 'CHALLENGE'
} as const

export type OrganizationPlanEnum = typeof OrganizationPlanEnum[keyof typeof OrganizationPlanEnum]
export const OrganizationPlanFrequencyEnum = {
  Month: 'MONTH',
  Year: 'YEAR'
} as const

export type OrganizationPlanFrequencyEnum =
  typeof OrganizationPlanFrequencyEnum[keyof typeof OrganizationPlanFrequencyEnum]
