/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface OrganizationUpdateSubscription
 */
export interface OrganizationUpdateSubscription {
  /**
   *
   * @type {string}
   * @memberof OrganizationUpdateSubscription
   */
  stripePriceId?: string
  /**
   *
   * @type {number}
   * @memberof OrganizationUpdateSubscription
   */
  totalSeats?: number
}
