/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ParticipantJoinInfo
 */
export interface ParticipantJoinInfo {
  /**
   *
   * @type {string}
   * @memberof ParticipantJoinInfo
   */
  joinId?: string
  /**
   *
   * @type {number}
   * @memberof ParticipantJoinInfo
   */
  joinedOn?: number
}
