/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ParticipantData
 */
export interface ParticipantData {
  /**
   *
   * @type {string}
   * @memberof ParticipantData
   */
  firstName?: string
  /**
   *
   * @type {boolean}
   * @memberof ParticipantData
   */
  flagged?: boolean
  /**
   *
   * @type {string}
   * @memberof ParticipantData
   */
  lastName?: string
  /**
   *
   * @type {string}
   * @memberof ParticipantData
   */
  participantUuid?: string
  /**
   *
   * @type {string}
   * @memberof ParticipantData
   */
  profileImage?: string
}
