/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface PaymentMethod
 */
export interface PaymentMethod {
  /**
   *
   * @type {string}
   * @memberof PaymentMethod
   */
  billingAddressCity?: string
  /**
   *
   * @type {string}
   * @memberof PaymentMethod
   */
  billingAddressCountry?: string
  /**
   *
   * @type {string}
   * @memberof PaymentMethod
   */
  billingAddressLine1?: string
  /**
   *
   * @type {string}
   * @memberof PaymentMethod
   */
  billingAddressLine2?: string
  /**
   *
   * @type {string}
   * @memberof PaymentMethod
   */
  billingAddressName?: string
  /**
   *
   * @type {string}
   * @memberof PaymentMethod
   */
  billingAddressPhone?: string
  /**
   *
   * @type {string}
   * @memberof PaymentMethod
   */
  billingAddressState?: string
  /**
   *
   * @type {string}
   * @memberof PaymentMethod
   */
  billingAddressZip?: string
  /**
   *
   * @type {string}
   * @memberof PaymentMethod
   */
  cardCountry?: string
  /**
   *
   * @type {string}
   * @memberof PaymentMethod
   */
  cardLast4?: string
  /**
   *
   * @type {string}
   * @memberof PaymentMethod
   */
  cardType?: string
  /**
   *
   * @type {number}
   * @memberof PaymentMethod
   */
  createdTs?: number
  /**
   *
   * @type {number}
   * @memberof PaymentMethod
   */
  expiryMonth?: number
  /**
   *
   * @type {number}
   * @memberof PaymentMethod
   */
  expiryYear?: number
}
