/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface PendingRenewalInfo
 */
export interface PendingRenewalInfo {
  /**
   *
   * @type {string}
   * @memberof PendingRenewalInfo
   */
  auto_renew_product_id?: string
  /**
   *
   * @type {string}
   * @memberof PendingRenewalInfo
   */
  auto_renew_status?: string
  /**
   *
   * @type {string}
   * @memberof PendingRenewalInfo
   */
  expiration_intent?: string
  /**
   *
   * @type {string}
   * @memberof PendingRenewalInfo
   */
  is_in_billing_retry_period?: string
  /**
   *
   * @type {string}
   * @memberof PendingRenewalInfo
   */
  original_transaction_id?: string
  /**
   *
   * @type {string}
   * @memberof PendingRenewalInfo
   */
  product_id?: string
}
