/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EmbeddedReminder } from './embedded-reminder'
import { Task1 } from './task1'

/**
 *
 * @export
 * @interface Plan1
 */
export interface Plan1 {
  /**
   *
   * @type {boolean}
   * @memberof Plan1
   */
  complete?: boolean
  /**
   *
   * @type {string}
   * @memberof Plan1
   */
  completedDate?: string
  /**
   *
   * @type {number}
   * @memberof Plan1
   */
  createTimestamp?: number
  /**
   *
   * @type {number}
   * @memberof Plan1
   */
  deleteTimestamp?: number
  /**
   *
   * @type {string}
   * @memberof Plan1
   */
  dueDateTimestamp?: string
  /**
   *
   * @type {string}
   * @memberof Plan1
   */
  id?: string
  /**
   *
   * @type {boolean}
   * @memberof Plan1
   */
  linked?: boolean
  /**
   *
   * @type {boolean}
   * @memberof Plan1
   */
  masterLink?: boolean
  /**
   *
   * @type {string}
   * @memberof Plan1
   */
  notes?: string
  /**
   *
   * @type {{ [key: string]: string; }}
   * @memberof Plan1
   */
  notesPhotosIds?: { [key: string]: string }
  /**
   *
   * @type {string}
   * @memberof Plan1
   */
  order?: string
  /**
   *
   * @type {EmbeddedReminder}
   * @memberof Plan1
   */
  reminder?: EmbeddedReminder
  /**
   *
   * @type {Array<Task1>}
   * @memberof Plan1
   */
  tasks?: Array<Task1>
  /**
   *
   * @type {string}
   * @memberof Plan1
   */
  title?: string
  /**
   *
   * @type {number}
   * @memberof Plan1
   */
  updateTimestamp?: number
  /**
   *
   * @type {string}
   * @memberof Plan1
   */
  uuid?: string
}
