/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EmbeddedReminderRequest } from './embedded-reminder-request'

/**
 *
 * @export
 * @interface PlanCreateRequest
 */
export interface PlanCreateRequest {
  /**
   *
   * @type {string}
   * @memberof PlanCreateRequest
   */
  dueDateTimestamp?: string
  /**
   *
   * @type {string}
   * @memberof PlanCreateRequest
   */
  masterOptionalId?: string
  /**
   *
   * @type {string}
   * @memberof PlanCreateRequest
   */
  masterPrimaryId?: string
  /**
   *
   * @type {string}
   * @memberof PlanCreateRequest
   */
  masterSecondaryId?: string
  /**
   *
   * @type {string}
   * @memberof PlanCreateRequest
   */
  notes?: string
  /**
   *
   * @type {EmbeddedReminderRequest}
   * @memberof PlanCreateRequest
   */
  reminder?: EmbeddedReminderRequest
  /**
   *
   * @type {string}
   * @memberof PlanCreateRequest
   */
  title?: string
  /**
   *
   * @type {string}
   * @memberof PlanCreateRequest
   */
  type?: PlanCreateRequestTypeEnum
  /**
   *
   * @type {boolean}
   * @memberof PlanCreateRequest
   */
  undo?: boolean
}

export const PlanCreateRequestTypeEnum = {
  Challenge: 'CHALLENGE',
  Journal: 'JOURNAL',
  Goal: 'GOAL',
  Plan: 'PLAN'
} as const

export type PlanCreateRequestTypeEnum = typeof PlanCreateRequestTypeEnum[keyof typeof PlanCreateRequestTypeEnum]
