/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface PlatformInformation
 */
export interface PlatformInformation {
  /**
   *
   * @type {string}
   * @memberof PlatformInformation
   */
  advertising_id?: string
  /**
   *
   * @type {string}
   * @memberof PlatformInformation
   */
  app_store?: string
  /**
   *
   * @type {string}
   * @memberof PlatformInformation
   */
  app_version_name?: string
  /**
   *
   * @type {string}
   * @memberof PlatformInformation
   */
  appsflyerAndroidId?: string
  /**
   *
   * @type {string}
   * @memberof PlatformInformation
   */
  appsflyerIOSId?: string
  /**
   *
   * @type {string}
   * @memberof PlatformInformation
   */
  appsflyerWebId?: string
  /**
   *
   * @type {number}
   * @memberof PlatformInformation
   */
  att?: number
  /**
   *
   * @type {string}
   * @memberof PlatformInformation
   */
  bundleIdentifier?: string
  /**
   *
   * @type {string}
   * @memberof PlatformInformation
   */
  idfa?: string
  /**
   *
   * @type {string}
   * @memberof PlatformInformation
   */
  idfv?: string
  /**
   *
   * @type {string}
   * @memberof PlatformInformation
   */
  imei?: string
  /**
   *
   * @type {string}
   * @memberof PlatformInformation
   */
  oaid?: string
  /**
   *
   * @type {string}
   * @memberof PlatformInformation
   */
  platform?: PlatformInformationPlatformEnum
}

export const PlatformInformationPlatformEnum = {
  Web: 'WEB',
  Ios: 'IOS',
  Android: 'ANDROID'
} as const

export type PlatformInformationPlatformEnum =
  typeof PlatformInformationPlatformEnum[keyof typeof PlatformInformationPlatformEnum]
