/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface PremiereDateCountdown
 */
export interface PremiereDateCountdown {
  /**
   *
   * @type {number}
   * @memberof PremiereDateCountdown
   */
  days?: number
  /**
   *
   * @type {number}
   * @memberof PremiereDateCountdown
   */
  hours?: number
  /**
   *
   * @type {number}
   * @memberof PremiereDateCountdown
   */
  minutes?: number
}
