/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Price
 */
export interface Price {
  /**
   *
   * @type {number}
   * @memberof Price
   */
  amount?: number
  /**
   *
   * @type {number}
   * @memberof Price
   */
  createdTs?: number
  /**
   *
   * @type {string}
   * @memberof Price
   */
  currency?: string
  /**
   *
   * @type {string}
   * @memberof Price
   */
  description?: string
  /**
   *
   * @type {string}
   * @memberof Price
   */
  interval?: string
  /**
   *
   * @type {string}
   * @memberof Price
   */
  name?: string
  /**
   *
   * @type {string}
   * @memberof Price
   */
  priceId?: string
  /**
   *
   * @type {string}
   * @memberof Price
   */
  productId?: string
}
