/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Profile
 */
export interface Profile {
  /**
   *
   * @type {string}
   * @memberof Profile
   */
  backgroundImageKey?: string
  /**
   *
   * @type {string}
   * @memberof Profile
   */
  bigWhyText?: string
  /**
   *
   * @type {Array<string>}
   * @memberof Profile
   */
  focusAreas?: Array<string>
}
