/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Profile } from './profile'

/**
 *
 * @export
 * @interface ProfileResponseWithCoinsCount
 */
export interface ProfileResponseWithCoinsCount {
  /**
   *
   * @type {number}
   * @memberof ProfileResponseWithCoinsCount
   */
  coinsEarnedThisTime?: number
  /**
   *
   * @type {number}
   * @memberof ProfileResponseWithCoinsCount
   */
  currentCoinCount?: number
  /**
   *
   * @type {Profile}
   * @memberof ProfileResponseWithCoinsCount
   */
  profile?: Profile
}
