/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Quarterly
 */
export interface Quarterly {
  /**
   *
   * @type {number}
   * @memberof Quarterly
   */
  count?: number
  /**
   *
   * @type {string}
   * @memberof Quarterly
   */
  endDate?: string
  /**
   *
   * @type {string}
   * @memberof Quarterly
   */
  startDate?: string
}
