/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AllTime } from './all-time'
import { Quarterly } from './quarterly'

/**
 *
 * @export
 * @interface QuarterlyCoins
 */
export interface QuarterlyCoins {
  /**
   *
   * @type {AllTime}
   * @memberof QuarterlyCoins
   */
  allTime?: AllTime
  /**
   *
   * @type {Quarterly}
   * @memberof QuarterlyCoins
   */
  quarterly?: Quarterly
}
