/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LatestReceiptInfo } from './latest-receipt-info'
import { PendingRenewalInfo } from './pending-renewal-info'
import { Receipt } from './receipt'

/**
 *
 * @export
 * @interface ReceiptDetails
 */
export interface ReceiptDetails {
  /**
   *
   * @type {string}
   * @memberof ReceiptDetails
   */
  environment?: string
  /**
   *
   * @type {string}
   * @memberof ReceiptDetails
   */
  latest_receipt?: string
  /**
   *
   * @type {Array<LatestReceiptInfo>}
   * @memberof ReceiptDetails
   */
  latest_receipt_info?: Array<LatestReceiptInfo>
  /**
   *
   * @type {Array<PendingRenewalInfo>}
   * @memberof ReceiptDetails
   */
  pending_renewal_info?: Array<PendingRenewalInfo>
  /**
   *
   * @type {Receipt}
   * @memberof ReceiptDetails
   */
  receipt?: Receipt
  /**
   *
   * @type {number}
   * @memberof ReceiptDetails
   */
  status?: number
}
