/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ReinviteUserResponse
 */
export interface ReinviteUserResponse {
  /**
   *
   * @type {number}
   * @memberof ReinviteUserResponse
   */
  failedReinviteCount?: number
  /**
   *
   * @type {{ [key: string]: string; }}
   * @memberof ReinviteUserResponse
   */
  failureReason?: { [key: string]: string }
  /**
   *
   * @type {number}
   * @memberof ReinviteUserResponse
   */
  successfulReinviteCount?: number
}
