/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ReminderTitles } from './reminder-titles'

/**
 *
 * @export
 * @interface Reminder
 */
export interface Reminder {
  /**
   *
   * @type {boolean}
   * @memberof Reminder
   */
  active?: boolean
  /**
   *
   * @type {string}
   * @memberof Reminder
   */
  body?: string
  /**
   *
   * @type {number}
   * @memberof Reminder
   */
  createTimestamp?: number
  /**
   *
   * @type {number}
   * @memberof Reminder
   */
  deleteTimestamp?: number
  /**
   *
   * @type {string}
   * @memberof Reminder
   */
  endTime?: string
  /**
   *
   * @type {string}
   * @memberof Reminder
   */
  entityId?: string
  /**
   *
   * @type {string}
   * @memberof Reminder
   */
  header?: string
  /**
   *
   * @type {string}
   * @memberof Reminder
   */
  id?: string
  /**
   *
   * @type {Array<string>}
   * @memberof Reminder
   */
  mediums?: Array<ReminderMediumsEnum>
  /**
   *
   * @type {string}
   * @memberof Reminder
   */
  rrule?: string
  /**
   *
   * @type {string}
   * @memberof Reminder
   */
  startTime?: string
  /**
   *
   * @type {ReminderTitles}
   * @memberof Reminder
   */
  titles?: ReminderTitles
  /**
   *
   * @type {string}
   * @memberof Reminder
   */
  type?: ReminderTypeEnum
  /**
   *
   * @type {string}
   * @memberof Reminder
   */
  until?: string
  /**
   *
   * @type {number}
   * @memberof Reminder
   */
  updateTimestamp?: number
  /**
   *
   * @type {string}
   * @memberof Reminder
   */
  uuid?: string
}

export const ReminderMediumsEnum = {
  InApp: 'IN_APP',
  Push: 'PUSH'
} as const

export type ReminderMediumsEnum = typeof ReminderMediumsEnum[keyof typeof ReminderMediumsEnum]
export const ReminderTypeEnum = {
  PlanSubTask: 'PLAN_SUB_TASK',
  PlanAction: 'PLAN_ACTION',
  PlanActionInsideChallenge: 'PLAN_ACTION_INSIDE_CHALLENGE',
  Plan: 'PLAN',
  PlanInsideChallenge: 'PLAN_INSIDE_CHALLENGE',
  Custom: 'CUSTOM'
} as const

export type ReminderTypeEnum = typeof ReminderTypeEnum[keyof typeof ReminderTypeEnum]
