/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Lead } from './lead'

/**
 *
 * @export
 * @interface Reward
 */
export interface Reward {
  /**
   *
   * @type {number}
   * @memberof Reward
   */
  amount?: number
  /**
   *
   * @type {number}
   * @memberof Reward
   */
  conversion_amount?: number
  /**
   *
   * @type {string}
   * @memberof Reward
   */
  created_at?: string
  /**
   *
   * @type {string}
   * @memberof Reward
   */
  event_id?: string
  /**
   *
   * @type {number}
   * @memberof Reward
   */
  id?: number
  /**
   *
   * @type {Lead}
   * @memberof Reward
   */
  lead?: Lead
  /**
   *
   * @type {string}
   * @memberof Reward
   */
  parsedDate?: string
  /**
   *
   * @type {string}
   * @memberof Reward
   */
  status?: string
  /**
   *
   * @type {string}
   * @memberof Reward
   */
  unit?: string
}
