/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface StripeTaxRequest
 */
export interface StripeTaxRequest {
  /**
   *
   * @type {string}
   * @memberof StripeTaxRequest
   */
  priceId?: string
  /**
   *
   * @type {string}
   * @memberof StripeTaxRequest
   */
  priceType?: StripeTaxRequestPriceTypeEnum
  /**
   *
   * @type {number}
   * @memberof StripeTaxRequest
   */
  quantity?: number
}

export const StripeTaxRequestPriceTypeEnum = {
  Plan: 'PLAN',
  Offer: 'OFFER'
} as const

export type StripeTaxRequestPriceTypeEnum =
  typeof StripeTaxRequestPriceTypeEnum[keyof typeof StripeTaxRequestPriceTypeEnum]
