/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { StripeTaxResponseItem } from './stripe-tax-response-item'

/**
 *
 * @export
 * @interface StripeTaxResponse
 */
export interface StripeTaxResponse {
  /**
   *
   * @type {Array<StripeTaxResponseItem>}
   * @memberof StripeTaxResponse
   */
  items?: Array<StripeTaxResponseItem>
  /**
   *
   * @type {number}
   * @memberof StripeTaxResponse
   */
  subTotalInCents?: number
  /**
   *
   * @type {number}
   * @memberof StripeTaxResponse
   */
  taxInCents?: number
  /**
   *
   * @type {number}
   * @memberof StripeTaxResponse
   */
  totalInCents?: number
}
