/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EmbeddedReminderRequest } from './embedded-reminder-request'

/**
 *
 * @export
 * @interface SubTaskPatchRequest
 */
export interface SubTaskPatchRequest {
  /**
   *
   * @type {boolean}
   * @memberof SubTaskPatchRequest
   */
  complete?: boolean
  /**
   *
   * @type {string}
   * @memberof SubTaskPatchRequest
   */
  dueDateTimestamp?: string
  /**
   *
   * @type {string}
   * @memberof SubTaskPatchRequest
   */
  notes?: string
  /**
   *
   * @type {{ [key: string]: string; }}
   * @memberof SubTaskPatchRequest
   */
  notesPhotosIds?: { [key: string]: string }
  /**
   *
   * @type {EmbeddedReminderRequest}
   * @memberof SubTaskPatchRequest
   */
  reminder?: EmbeddedReminderRequest
  /**
   *
   * @type {string}
   * @memberof SubTaskPatchRequest
   */
  title?: string
}
