/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface SubscriptionDetails
 */
export interface SubscriptionDetails {
  /**
   *
   * @type {number}
   * @memberof SubscriptionDetails
   */
  amount?: number
  /**
   *
   * @type {number}
   * @memberof SubscriptionDetails
   */
  nextBilling?: number
  /**
   *
   * @type {number}
   * @memberof SubscriptionDetails
   */
  outstandingBalance?: number
  /**
   *
   * @type {string}
   * @memberof SubscriptionDetails
   */
  planId?: string
  /**
   *
   * @type {string}
   * @memberof SubscriptionDetails
   */
  planName?: string
  /**
   *
   * @type {string}
   * @memberof SubscriptionDetails
   */
  priceId?: string
  /**
   *
   * @type {number}
   * @memberof SubscriptionDetails
   */
  startTime?: number
  /**
   *
   * @type {string}
   * @memberof SubscriptionDetails
   */
  type?: string
}
