/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Achievement } from './achievement'
import { PostAssessmentCreationMessage } from './post-assessment-creation-message'
import { TeamAssessment } from './team-assessment'

/**
 *
 * @export
 * @interface TeamAssessmentResponse
 */
export interface TeamAssessmentResponse {
  /**
   *
   * @type {Achievement}
   * @memberof TeamAssessmentResponse
   */
  achievement?: Achievement
  /**
   *
   * @type {number}
   * @memberof TeamAssessmentResponse
   */
  coinsEarnedThisTime?: number
  /**
   *
   * @type {number}
   * @memberof TeamAssessmentResponse
   */
  currentCoinCount?: number
  /**
   *
   * @type {PostAssessmentCreationMessage}
   * @memberof TeamAssessmentResponse
   */
  message?: PostAssessmentCreationMessage
  /**
   *
   * @type {TeamAssessment}
   * @memberof TeamAssessmentResponse
   */
  teamAssessment?: TeamAssessment
}
