/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AssessmentPercentage } from './assessment-percentage'

/**
 *
 * @export
 * @interface TeamAssessment
 */
export interface TeamAssessment {
  /**
   *
   * @type {{ [key: string]: Array<AssessmentPercentage>; }}
   * @memberof TeamAssessment
   */
  assessmentPercentage?: { [key: string]: Array<AssessmentPercentage> }
  /**
   *
   * @type {number}
   * @memberof TeamAssessment
   */
  createTimestamp?: number
  /**
   *
   * @type {number}
   * @memberof TeamAssessment
   */
  deleteTimestamp?: number
  /**
   *
   * @type {string}
   * @memberof TeamAssessment
   */
  departmentId?: string
  /**
   *
   * @type {string}
   * @memberof TeamAssessment
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof TeamAssessment
   */
  organizationId?: string
  /**
   *
   * @type {{ [key: string]: { [key: string]: number; }; }}
   * @memberof TeamAssessment
   */
  scoreCard?: { [key: string]: { [key: string]: number } }
  /**
   *
   * @type {string}
   * @memberof TeamAssessment
   */
  type?: TeamAssessmentTypeEnum
  /**
   *
   * @type {number}
   * @memberof TeamAssessment
   */
  updateTimestamp?: number
  /**
   *
   * @type {string}
   * @memberof TeamAssessment
   */
  uuid?: string
}

export const TeamAssessmentTypeEnum = {
  Daily: 'DAILY',
  Weekly: 'WEEKLY',
  Monthly: 'MONTHLY',
  TeamAssessment: 'TEAM_ASSESSMENT'
} as const

export type TeamAssessmentTypeEnum = typeof TeamAssessmentTypeEnum[keyof typeof TeamAssessmentTypeEnum]
