/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Duration } from './duration'

/**
 *
 * @export
 * @interface TemporalUnit
 */
export interface TemporalUnit {
  /**
   *
   * @type {boolean}
   * @memberof TemporalUnit
   */
  dateBased?: boolean
  /**
   *
   * @type {Duration}
   * @memberof TemporalUnit
   */
  duration?: Duration
  /**
   *
   * @type {boolean}
   * @memberof TemporalUnit
   */
  durationEstimated?: boolean
  /**
   *
   * @type {boolean}
   * @memberof TemporalUnit
   */
  timeBased?: boolean
}
