/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Transaction
 */
export interface Transaction {
  /**
   *
   * @type {number}
   * @memberof Transaction
   */
  amount?: number
  /**
   *
   * @type {number}
   * @memberof Transaction
   */
  createdTs?: number
  /**
   *
   * @type {string}
   * @memberof Transaction
   */
  currency?: string
  /**
   *
   * @type {string}
   * @memberof Transaction
   */
  description?: string
  /**
   *
   * @type {string}
   * @memberof Transaction
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof Transaction
   */
  type?: string
}
