/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UserFilter
 */
export interface UserFilter {
  /**
   *
   * @type {boolean}
   * @memberof UserFilter
   */
  demoUser?: boolean
  /**
   *
   * @type {string}
   * @memberof UserFilter
   */
  email?: string
  /**
   *
   * @type {boolean}
   * @memberof UserFilter
   */
  kajabiUser?: boolean
  /**
   *
   * @type {string}
   * @memberof UserFilter
   */
  level?: UserFilterLevelEnum
  /**
   *
   * @type {number}
   * @memberof UserFilter
   */
  limit?: number
  /**
   *
   * @type {string}
   * @memberof UserFilter
   */
  name?: string
  /**
   *
   * @type {number}
   * @memberof UserFilter
   */
  offset?: number
  /**
   *
   * @type {string}
   * @memberof UserFilter
   */
  phoneNumber?: string
  /**
   *
   * @type {boolean}
   * @memberof UserFilter
   */
  subscriptionCancelled?: boolean
}

export const UserFilterLevelEnum = {
  Basic: 'BASIC',
  Growth: 'GROWTH',
  Mastery: 'MASTERY',
  Trial: 'TRIAL',
  None: 'NONE',
  Offer: 'OFFER',
  Challenge: 'CHALLENGE',
  Enterprise: 'ENTERPRISE',
  Allaccess: 'ALLACCESS'
} as const

export type UserFilterLevelEnum = typeof UserFilterLevelEnum[keyof typeof UserFilterLevelEnum]
