/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UserInviteGiftSubscriptionRequest
 */
export interface UserInviteGiftSubscriptionRequest {
  /**
   *
   * @type {string}
   * @memberof UserInviteGiftSubscriptionRequest
   */
  countryCode?: string
  /**
   *
   * @type {string}
   * @memberof UserInviteGiftSubscriptionRequest
   */
  email?: string
  /**
   *
   * @type {string}
   * @memberof UserInviteGiftSubscriptionRequest
   */
  fullName?: string
  /**
   *
   * @type {string}
   * @memberof UserInviteGiftSubscriptionRequest
   */
  iso2?: string
  /**
   *
   * @type {string}
   * @memberof UserInviteGiftSubscriptionRequest
   */
  newPassword?: string
  /**
   *
   * @type {string}
   * @memberof UserInviteGiftSubscriptionRequest
   */
  phoneNumber?: string
  /**
   *
   * @type {string}
   * @memberof UserInviteGiftSubscriptionRequest
   */
  token?: string
}
