/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UserNote
 */
export interface UserNote {
  /**
   *
   * @type {string}
   * @memberof UserNote
   */
  content?: string
  /**
   *
   * @type {number}
   * @memberof UserNote
   */
  createTimestamp?: number
  /**
   *
   * @type {number}
   * @memberof UserNote
   */
  deleteTimestamp?: number
  /**
   *
   * @type {string}
   * @memberof UserNote
   */
  entityId?: string
  /**
   *
   * @type {string}
   * @memberof UserNote
   */
  entityType?: UserNoteEntityTypeEnum
  /**
   *
   * @type {string}
   * @memberof UserNote
   */
  id?: string
  /**
   *
   * @type {{ [key: string]: string; }}
   * @memberof UserNote
   */
  notePhotos?: { [key: string]: string }
  /**
   *
   * @type {boolean}
   * @memberof UserNote
   */
  pinned?: boolean
  /**
   *
   * @type {string}
   * @memberof UserNote
   */
  subEntityId?: string
  /**
   *
   * @type {boolean}
   * @memberof UserNote
   */
  textNote?: boolean
  /**
   *
   * @type {number}
   * @memberof UserNote
   */
  timeCode?: number
  /**
   *
   * @type {number}
   * @memberof UserNote
   */
  updateTimestamp?: number
  /**
   *
   * @type {string}
   * @memberof UserNote
   */
  uuid?: string
}

export const UserNoteEntityTypeEnum = {
  GrowthGroup: 'GROWTH_GROUP',
  LiveEvent: 'LIVE_EVENT',
  Course: 'COURSE',
  Challenge: 'CHALLENGE'
} as const

export type UserNoteEntityTypeEnum = typeof UserNoteEntityTypeEnum[keyof typeof UserNoteEntityTypeEnum]
