/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UserNotificationInfo
 */
export interface UserNotificationInfo {
  /**
   *
   * @type {boolean}
   * @memberof UserNotificationInfo
   */
  planToBeCreated?: boolean
}
