/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UserNoteRequest
 */
export interface UserNoteRequest {
  /**
   *
   * @type {string}
   * @memberof UserNoteRequest
   */
  content?: string
  /**
   *
   * @type {string}
   * @memberof UserNoteRequest
   */
  entityId?: string
  /**
   *
   * @type {string}
   * @memberof UserNoteRequest
   */
  entityType?: UserNoteRequestEntityTypeEnum
  /**
   *
   * @type {string}
   * @memberof UserNoteRequest
   */
  subEntityId?: string
}

export const UserNoteRequestEntityTypeEnum = {
  GrowthGroup: 'GROWTH_GROUP'
} as const

export type UserNoteRequestEntityTypeEnum =
  typeof UserNoteRequestEntityTypeEnum[keyof typeof UserNoteRequestEntityTypeEnum]
