/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UserMetadata
 */
export interface UserMetadata {
  /**
   *
   * @type {number}
   * @memberof UserMetadata
   */
  createTimestamp?: number
  /**
   *
   * @type {boolean}
   * @memberof UserMetadata
   */
  deactivatedEnterpriseAccount?: boolean
  /**
   *
   * @type {number}
   * @memberof UserMetadata
   */
  deleteTimestamp?: number
  /**
   *
   * @type {string}
   * @memberof UserMetadata
   */
  enterpriseSubscriptionGiftedBy?: string
  /**
   *
   * @type {number}
   * @memberof UserMetadata
   */
  growthGroupUpsellPopupCount?: number
  /**
   *
   * @type {string}
   * @memberof UserMetadata
   */
  id?: string
  /**
   *
   * @type {boolean}
   * @memberof UserMetadata
   */
  readCommunityGuideline?: boolean
  /**
   *
   * @type {boolean}
   * @memberof UserMetadata
   */
  readCreationCommunityGuideline?: boolean
  /**
   *
   * @type {boolean}
   * @memberof UserMetadata
   */
  showTransferAccountTerms?: boolean
  /**
   *
   * @type {boolean}
   * @memberof UserMetadata
   */
  transferEnterpriseAccount?: boolean
  /**
   *
   * @type {number}
   * @memberof UserMetadata
   */
  updateTimestamp?: number
  /**
   *
   * @type {string}
   * @memberof UserMetadata
   */
  userId?: string
  /**
   *
   * @type {string}
   * @memberof UserMetadata
   */
  uuid?: string
}
