/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LessonProgress } from './lesson-progress'
import { UserCourseNote } from './user-course-note'

/**
 *
 * @export
 * @interface UserCourse
 */
export interface UserCourse {
  /**
   *
   * @type {boolean}
   * @memberof UserCourse
   */
  complete?: boolean
  /**
   *
   * @type {string}
   * @memberof UserCourse
   */
  completedDate?: string
  /**
   *
   * @type {number}
   * @memberof UserCourse
   */
  courseId?: number
  /**
   *
   * @type {number}
   * @memberof UserCourse
   */
  createTimestamp?: number
  /**
   *
   * @type {number}
   * @memberof UserCourse
   */
  deleteTimestamp?: number
  /**
   *
   * @type {string}
   * @memberof UserCourse
   */
  id?: string
  /**
   *
   * @type {Array<LessonProgress>}
   * @memberof UserCourse
   */
  lessonProgress?: Array<LessonProgress>
  /**
   *
   * @type {boolean}
   * @memberof UserCourse
   */
  noteMigrated?: boolean
  /**
   *
   * @type {Array<UserCourseNote>}
   * @memberof UserCourse
   */
  notes?: Array<UserCourseNote>
  /**
   *
   * @type {number}
   * @memberof UserCourse
   */
  updateTimestamp?: number
  /**
   *
   * @type {string}
   * @memberof UserCourse
   */
  uuid?: string
}
