/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UserTourUpdateRequest
 */
export interface UserTourUpdateRequest {
  /**
   *
   * @type {string}
   * @memberof UserTourUpdateRequest
   */
  trigger?: UserTourUpdateRequestTriggerEnum
  /**
   *
   * @type {string}
   * @memberof UserTourUpdateRequest
   */
  triggerId?: string
  /**
   *
   * @type {string}
   * @memberof UserTourUpdateRequest
   */
  triggerType?: UserTourUpdateRequestTriggerTypeEnum
}

export const UserTourUpdateRequestTriggerEnum = {
  ChallengeDayOneComplete: 'ON_CHALLENGE_DAY_ONE_COMPLETE',
  ChallengeLoad: 'ON_CHALLENGE_LOAD',
  ChallengeFirstTaskComplete: 'ON_CHALLENGE_FIRST_TASK_COMPLETE',
  DashboardLoad: 'ON_DASHBOARD_LOAD',
  EnterpriseDashboardLoad: 'ON_ENTERPRISE_DASHBOARD_LOAD'
} as const

export type UserTourUpdateRequestTriggerEnum =
  typeof UserTourUpdateRequestTriggerEnum[keyof typeof UserTourUpdateRequestTriggerEnum]
export const UserTourUpdateRequestTriggerTypeEnum = {
  Challenge: 'CHALLENGE',
  Plan: 'PLAN',
  Offer: 'OFFER',
  Campaign: 'CAMPAIGN',
  EnterpriseAdmin: 'ENTERPRISE_ADMIN'
} as const

export type UserTourUpdateRequestTriggerTypeEnum =
  typeof UserTourUpdateRequestTriggerTypeEnum[keyof typeof UserTourUpdateRequestTriggerTypeEnum]
