/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Achievement } from './achievement'
import { UserCourse } from './user-course'

/**
 *
 * @export
 * @interface UserCourseResponse
 */
export interface UserCourseResponse {
  /**
   *
   * @type {Achievement}
   * @memberof UserCourseResponse
   */
  achievement?: Achievement
  /**
   *
   * @type {number}
   * @memberof UserCourseResponse
   */
  coinsEarnedThisTime?: number
  /**
   *
   * @type {number}
   * @memberof UserCourseResponse
   */
  currentCoinCount?: number
  /**
   *
   * @type {UserCourse}
   * @memberof UserCourseResponse
   */
  userCourse?: UserCourse
}
