/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UserCourse } from './user-course'

/**
 *
 * @export
 * @interface UserCoursesList
 */
export interface UserCoursesList {
  /**
   *
   * @type {number}
   * @memberof UserCoursesList
   */
  count?: number
  /**
   *
   * @type {Array<UserCourse>}
   * @memberof UserCoursesList
   */
  list?: Array<UserCourse>
}
