/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UserCourseNoteResponse
 */
export interface UserCourseNoteResponse {
  /**
   *
   * @type {string}
   * @memberof UserCourseNoteResponse
   */
  noteContent?: string
  /**
   *
   * @type {string}
   * @memberof UserCourseNoteResponse
   */
  noteId?: string
  /**
   *
   * @type {boolean}
   * @memberof UserCourseNoteResponse
   */
  pinned?: boolean
  /**
   *
   * @type {boolean}
   * @memberof UserCourseNoteResponse
   */
  textNote?: boolean
  /**
   *
   * @type {number}
   * @memberof UserCourseNoteResponse
   */
  timeCode?: number
  /**
   *
   * @type {number}
   * @memberof UserCourseNoteResponse
   */
  timestamp?: number
}
