/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PlatformInformation } from './platform-information'
import { Profile } from './profile'
import { UserChatProfile } from './user-chat-profile'
import { UserNotificationInfo } from './user-notification-info'
import { UserPreferences } from './user-preferences'

/**
 *
 * @export
 * @interface User
 */
export interface User {
  /**
   *
   * @type {boolean}
   * @memberof User
   */
  accountNonExpired?: boolean
  /**
   *
   * @type {boolean}
   * @memberof User
   */
  accountNonLocked?: boolean
  /**
   *
   * @type {boolean}
   * @memberof User
   */
  allowedToCreateGrowthGroup?: boolean
  /**
   *
   * @type {string}
   * @memberof User
   */
  applePlanId?: string
  /**
   *
   * @type {string}
   * @memberof User
   */
  appleSubscriptionId?: string
  /**
   *
   * @type {boolean}
   * @memberof User
   */
  authorizedForLiveEvents?: boolean
  /**
   *
   * @type {boolean}
   * @memberof User
   */
  automaticTaxEnabled?: boolean
  /**
   *
   * @type {number}
   * @memberof User
   */
  campaignId?: number
  /**
   *
   * @type {string}
   * @memberof User
   */
  country?: string
  /**
   *
   * @type {string}
   * @memberof User
   */
  countryCode?: string
  /**
   *
   * @type {number}
   * @memberof User
   */
  createTimestamp?: number
  /**
   *
   * @type {boolean}
   * @memberof User
   */
  credentialsNonExpired?: boolean
  /**
   *
   * @type {number}
   * @memberof User
   */
  currentBadgeCount?: number
  /**
   *
   * @type {number}
   * @memberof User
   */
  currentCertificateCount?: number
  /**
   *
   * @type {number}
   * @memberof User
   */
  currentCoinCount?: number
  /**
   *
   * @type {number}
   * @memberof User
   */
  deleteTimestamp?: number
  /**
   *
   * @type {boolean}
   * @memberof User
   */
  demoUser?: boolean
  /**
   *
   * @type {string}
   * @memberof User
   */
  email?: string
  /**
   *
   * @type {string}
   * @memberof User
   */
  emailStartsWith?: string
  /**
   *
   * @type {boolean}
   * @memberof User
   */
  enabled?: boolean
  /**
   *
   * @type {boolean}
   * @memberof User
   */
  enterpriseUser?: boolean
  /**
   *
   * @type {boolean}
   * @memberof User
   */
  expired?: boolean
  /**
   *
   * @type {string}
   * @memberof User
   */
  firstPromoterAuthKey?: string
  /**
   *
   * @type {string}
   * @memberof User
   */
  firstPromoterCustomerId?: string
  /**
   *
   * @type {boolean}
   * @memberof User
   */
  forcePasswordChange?: boolean
  /**
   *
   * @type {string}
   * @memberof User
   */
  fullName?: string
  /**
   *
   * @type {boolean}
   * @memberof User
   */
  giftBuyer?: boolean
  /**
   *
   * @type {string}
   * @memberof User
   */
  giftSubscriptionBuyerEmail?: string
  /**
   *
   * @type {number}
   * @memberof User
   */
  giftSubscriptionRedemptionCount?: number
  /**
   *
   * @type {string}
   * @memberof User
   */
  giftSubscriptionSignupToken?: string
  /**
   *
   * @type {boolean}
   * @memberof User
   */
  hasAccessToMastermind?: boolean
  /**
   *
   * @type {string}
   * @memberof User
   */
  ianaTimezone?: string
  /**
   *
   * @type {string}
   * @memberof User
   */
  id?: string
  /**
   *
   * @type {boolean}
   * @memberof User
   */
  invalidSubscription?: boolean
  /**
   *
   * @type {string}
   * @memberof User
   */
  ipAddress?: string
  /**
   *
   * @type {boolean}
   * @memberof User
   */
  isActive?: boolean
  /**
   *
   * @type {boolean}
   * @memberof User
   */
  isGiftBuyer?: boolean
  /**
   *
   * @type {boolean}
   * @memberof User
   */
  isSubscriptionCancelled?: boolean
  /**
   *
   * @type {string}
   * @memberof User
   */
  iso2?: string
  /**
   *
   * @type {boolean}
   * @memberof User
   */
  joinedFirstEverLiveEvent?: boolean
  /**
   *
   * @type {boolean}
   * @memberof User
   */
  kajabiUser?: boolean
  /**
   *
   * @type {string}
   * @memberof User
   */
  keycloakUserUuid?: string
  /**
   *
   * @type {string}
   * @memberof User
   */
  level?: UserLevelEnum
  /**
   *
   * @type {boolean}
   * @memberof User
   */
  needPasswordSet?: boolean
  /**
   *
   * @type {UserNotificationInfo}
   * @memberof User
   */
  notificationInfo?: UserNotificationInfo
  /**
   *
   * @type {string}
   * @memberof User
   */
  oldSubscription?: string
  /**
   *
   * @type {boolean}
   * @memberof User
   */
  onboarded?: boolean
  /**
   *
   * @type {string}
   * @memberof User
   */
  oneSignalPlayerId?: string
  /**
   *
   * @type {boolean}
   * @memberof User
   */
  optInForResearch?: boolean
  /**
   *
   * @type {boolean}
   * @memberof User
   */
  paidUser?: boolean
  /**
   *
   * @type {number}
   * @memberof User
   */
  paymentAbandonmentReminderCount?: number
  /**
   *
   * @type {string}
   * @memberof User
   */
  paymentMethodId?: string
  /**
   *
   * @type {string}
   * @memberof User
   */
  paymentSystem?: UserPaymentSystemEnum
  /**
   *
   * @type {string}
   * @memberof User
   */
  paypalEmail?: string
  /**
   *
   * @type {string}
   * @memberof User
   */
  paypalNewSubscriptionPlanId?: string
  /**
   *
   * @type {string}
   * @memberof User
   */
  paypalPlanId?: string
  /**
   *
   * @type {string}
   * @memberof User
   */
  paypalSubscriptionId?: string
  /**
   *
   * @type {string}
   * @memberof User
   */
  phoneNumber?: string
  /**
   *
   * @type {string}
   * @memberof User
   */
  planFrequency?: UserPlanFrequencyEnum
  /**
   *
   * @type {string}
   * @memberof User
   */
  planId?: string
  /**
   *
   * @type {PlatformInformation}
   * @memberof User
   */
  platformInformation?: PlatformInformation
  /**
   *
   * @type {UserPreferences}
   * @memberof User
   */
  preferences?: UserPreferences
  /**
   *
   * @type {boolean}
   * @memberof User
   */
  proUser?: boolean
  /**
   *
   * @type {Profile}
   * @memberof User
   */
  profile?: Profile
  /**
   *
   * @type {boolean}
   * @memberof User
   */
  profileComplete?: boolean
  /**
   *
   * @type {string}
   * @memberof User
   */
  profileImageKey?: string
  /**
   *
   * @type {string}
   * @memberof User
   */
  region?: string
  /**
   *
   * @type {string}
   * @memberof User
   */
  registrationReferralCode?: string
  /**
   *
   * @type {string}
   * @memberof User
   */
  registrationReferralUserId?: string
  /**
   *
   * @type {number}
   * @memberof User
   */
  reportedFeedback?: number
  /**
   *
   * @type {number}
   * @memberof User
   */
  reportedIssues?: number
  /**
   *
   * @type {boolean}
   * @memberof User
   */
  shakeToFeedback?: boolean
  /**
   *
   * @type {number}
   * @memberof User
   */
  signupChallengeId?: number
  /**
   *
   * @type {string}
   * @memberof User
   */
  signupChallengeName?: string
  /**
   *
   * @type {string}
   * @memberof User
   */
  signupGrowthGroupInstanceId?: string
  /**
   *
   * @type {number}
   * @memberof User
   */
  signupId?: number
  /**
   *
   * @type {number}
   * @memberof User
   */
  signupLiveEventId?: number
  /**
   *
   * @type {number}
   * @memberof User
   */
  signupOfferId?: number
  /**
   *
   * @type {string}
   * @memberof User
   */
  signupOfferName?: string
  /**
   *
   * @type {number}
   * @memberof User
   */
  signupPlanId?: number
  /**
   *
   * @type {number}
   * @memberof User
   */
  signupSocialEventId?: number
  /**
   *
   * @type {string}
   * @memberof User
   */
  signupType?: UserSignupTypeEnum
  /**
   *
   * @type {string}
   * @memberof User
   */
  stripeCustomerId?: string
  /**
   *
   * @type {string}
   * @memberof User
   */
  stripePriceId?: string
  /**
   *
   * @type {string}
   * @memberof User
   */
  stripeSubscriptionId?: string
  /**
   *
   * @type {boolean}
   * @memberof User
   */
  subscriptionCancelled?: boolean
  /**
   *
   * @type {number}
   * @memberof User
   */
  subscriptionExpiry?: number
  /**
   *
   * @type {string}
   * @memberof User
   */
  subscriptionPlanName?: string
  /**
   *
   * @type {string}
   * @memberof User
   */
  subscriptionPlatform?: UserSubscriptionPlatformEnum
  /**
   *
   * @type {number}
   * @memberof User
   */
  trialPeriodEnd?: number
  /**
   *
   * @type {number}
   * @memberof User
   */
  trialReminderCount?: number
  /**
   *
   * @type {number}
   * @memberof User
   */
  updateTimestamp?: number
  /**
   *
   * @type {Array<string>}
   * @memberof User
   */
  userAttributes?: Array<string>
  /**
   *
   * @type {UserChatProfile}
   * @memberof User
   */
  userChatProfile?: UserChatProfile
  /**
   *
   * @type {string}
   * @memberof User
   */
  userProfileHash?: string
  /**
   *
   * @type {{ [key: string]: string; }}
   * @memberof User
   */
  userProperties?: { [key: string]: string }
  /**
   *
   * @type {string}
   * @memberof User
   */
  username?: string
  /**
   *
   * @type {number}
   * @memberof User
   */
  utcOffsetInMinutes?: number
  /**
   *
   * @type {string}
   * @memberof User
   */
  uuid?: string
  /**
   *
   * @type {string}
   * @memberof User
   */
  uuidAsUuid?: string
  /**
   *
   * @type {boolean}
   * @memberof User
   */
  webPlatform?: boolean
  /**
   *
   * @type {boolean}
   * @memberof User
   */
  webSubscriptionPlatform?: boolean
  /**
   *
   * @type {string}
   * @memberof User
   */
  zipCode?: string
}

export const UserLevelEnum = {
  Basic: 'BASIC',
  Growth: 'GROWTH',
  Mastery: 'MASTERY',
  Trial: 'TRIAL',
  None: 'NONE',
  Offer: 'OFFER',
  Challenge: 'CHALLENGE',
  Enterprise: 'ENTERPRISE',
  Allaccess: 'ALLACCESS'
} as const

export type UserLevelEnum = typeof UserLevelEnum[keyof typeof UserLevelEnum]
export const UserPaymentSystemEnum = {
  Card: 'CARD',
  Paypal: 'PAYPAL',
  Apple: 'APPLE'
} as const

export type UserPaymentSystemEnum = typeof UserPaymentSystemEnum[keyof typeof UserPaymentSystemEnum]
export const UserPlanFrequencyEnum = {
  Month: 'MONTH',
  Year: 'YEAR'
} as const

export type UserPlanFrequencyEnum = typeof UserPlanFrequencyEnum[keyof typeof UserPlanFrequencyEnum]
export const UserSignupTypeEnum = {
  Challenge: 'CHALLENGE',
  Offer: 'OFFER',
  LiveEvent: 'LIVE_EVENT',
  Plan: 'PLAN'
} as const

export type UserSignupTypeEnum = typeof UserSignupTypeEnum[keyof typeof UserSignupTypeEnum]
export const UserSubscriptionPlatformEnum = {
  Web: 'WEB',
  Ios: 'IOS',
  Android: 'ANDROID'
} as const

export type UserSubscriptionPlatformEnum =
  typeof UserSubscriptionPlatformEnum[keyof typeof UserSubscriptionPlatformEnum]
