/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UserPreferences
 */
export interface UserPreferences {
  /**
   *
   * @type {boolean}
   * @memberof UserPreferences
   */
  appChallengePlanActivities?: boolean
  /**
   *
   * @type {boolean}
   * @memberof UserPreferences
   */
  appKeepMeAccountable?: boolean
  /**
   *
   * @type {boolean}
   * @memberof UserPreferences
   */
  appLiveSession?: boolean
  /**
   *
   * @type {boolean}
   * @memberof UserPreferences
   */
  emailGrowthDayUpdates?: boolean
  /**
   *
   * @type {boolean}
   * @memberof UserPreferences
   */
  emailLiveEvents?: boolean
  /**
   *
   * @type {boolean}
   * @memberof UserPreferences
   */
  emailSundayNote?: boolean
  /**
   *
   * @type {boolean}
   * @memberof UserPreferences
   */
  emailWeeklyPerformance?: boolean
}
