/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UserAddressUpdateRequest
 */
export interface UserAddressUpdateRequest {
  /**
   *
   * @type {string}
   * @memberof UserAddressUpdateRequest
   */
  country?: string
  /**
   *
   * @type {string}
   * @memberof UserAddressUpdateRequest
   */
  countryCode?: string
  /**
   *
   * @type {string}
   * @memberof UserAddressUpdateRequest
   */
  iso2?: string
  /**
   *
   * @type {string}
   * @memberof UserAddressUpdateRequest
   */
  phoneNumber?: string
  /**
   *
   * @type {string}
   * @memberof UserAddressUpdateRequest
   */
  region?: string
  /**
   *
   * @type {string}
   * @memberof UserAddressUpdateRequest
   */
  zipCode?: string
}
