/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UserChatProfile
 */
export interface UserChatProfile {
  /**
   *
   * @type {string}
   * @memberof UserChatProfile
   */
  email?: string
  /**
   *
   * @type {string}
   * @memberof UserChatProfile
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof UserChatProfile
   */
  name?: string
  /**
   *
   * @type {string}
   * @memberof UserChatProfile
   */
  picture?: string
}
