/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UserNote } from './user-note'

/**
 *
 * @export
 * @interface UserNoteResponse
 */
export interface UserNoteResponse {
  /**
   *
   * @type {number}
   * @memberof UserNoteResponse
   */
  count?: number
  /**
   *
   * @type {Array<UserNote>}
   * @memberof UserNoteResponse
   */
  userNoteList?: Array<UserNote>
}
