/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SavedContent } from './saved-content'

/**
 *
 * @export
 * @interface UserList
 */
export interface UserList {
  /**
   *
   * @type {number}
   * @memberof UserList
   */
  createTimestamp?: number
  /**
   *
   * @type {number}
   * @memberof UserList
   */
  deleteTimestamp?: number
  /**
   *
   * @type {string}
   * @memberof UserList
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof UserList
   */
  listName?: string
  /**
   *
   * @type {Array<SavedContent>}
   * @memberof UserList
   */
  savedContentList?: Array<SavedContent>
  /**
   *
   * @type {number}
   * @memberof UserList
   */
  updateTimestamp?: number
  /**
   *
   * @type {string}
   * @memberof UserList
   */
  uuid?: string
}
