/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UserCourseLessonRequest
 */
export interface UserCourseLessonRequest {
  /**
   *
   * @type {boolean}
   * @memberof UserCourseLessonRequest
   */
  detectImage?: boolean
  /**
   *
   * @type {string}
   * @memberof UserCourseLessonRequest
   */
  notes?: string
  /**
   *
   * @type {number}
   * @memberof UserCourseLessonRequest
   */
  timeCode?: number
  /**
   *
   * @type {number}
   * @memberof UserCourseLessonRequest
   */
  videoTs?: number
}
