/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UserCourseNote
 */
export interface UserCourseNote {
  /**
   *
   * @type {number}
   * @memberof UserCourseNote
   */
  lessonId?: number
  /**
   *
   * @type {string}
   * @memberof UserCourseNote
   */
  noteContent?: string
  /**
   *
   * @type {string}
   * @memberof UserCourseNote
   */
  noteId?: string
  /**
   *
   * @type {{ [key: string]: string; }}
   * @memberof UserCourseNote
   */
  photosIds?: { [key: string]: string }
  /**
   *
   * @type {{ [key: string]: string; }}
   * @memberof UserCourseNote
   */
  photosUrls?: { [key: string]: string }
  /**
   *
   * @type {boolean}
   * @memberof UserCourseNote
   */
  pinned?: boolean
  /**
   *
   * @type {boolean}
   * @memberof UserCourseNote
   */
  textNote?: boolean
  /**
   *
   * @type {number}
   * @memberof UserCourseNote
   */
  timeCode?: number
  /**
   *
   * @type {number}
   * @memberof UserCourseNote
   */
  timestamp?: number
  /**
   *
   * @type {number}
   * @memberof UserCourseNote
   */
  updatedTs?: number
  /**
   *
   * @type {number}
   * @memberof UserCourseNote
   */
  videoTs?: number
}
