/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VideoCaption } from './video-caption'
import { VideoSource } from './video-source'

/**
 *
 * @export
 * @interface VideoResponse
 */
export interface VideoResponse {
  /**
   *
   * @type {Array<VideoCaption>}
   * @memberof VideoResponse
   */
  captions?: Array<VideoCaption>
  /**
   *
   * @type {Array<VideoSource>}
   * @memberof VideoResponse
   */
  sources?: Array<VideoSource>
  /**
   *
   * @type {string}
   * @memberof VideoResponse
   */
  thumbnail?: string
}
