/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface VideoCaption
 */
export interface VideoCaption {
  /**
   *
   * @type {string}
   * @memberof VideoCaption
   */
  label?: string
  /**
   *
   * @type {string}
   * @memberof VideoCaption
   */
  language?: string
  /**
   *
   * @type {string}
   * @memberof VideoCaption
   */
  text?: string
  /**
   *
   * @type {string}
   * @memberof VideoCaption
   */
  url?: string
}
