/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface WeeklyLifeScoreData
 */
export interface WeeklyLifeScoreData {
  /**
   *
   * @type {number}
   * @memberof WeeklyLifeScoreData
   */
  avgScore?: number
  /**
   *
   * @type {string}
   * @memberof WeeklyLifeScoreData
   */
  demonstratecourage?: string
  /**
   *
   * @type {string}
   * @memberof WeeklyLifeScoreData
   */
  developinfluence?: string
  /**
   *
   * @type {string}
   * @memberof WeeklyLifeScoreData
   */
  generateenergy?: string
  /**
   *
   * @type {string}
   * @memberof WeeklyLifeScoreData
   */
  increaseproductivity?: string
  /**
   *
   * @type {string}
   * @memberof WeeklyLifeScoreData
   */
  organizationId?: string
  /**
   *
   * @type {string}
   * @memberof WeeklyLifeScoreData
   */
  organizationName?: string
  /**
   *
   * @type {string}
   * @memberof WeeklyLifeScoreData
   */
  raisenecessity?: string
  /**
   *
   * @type {string}
   * @memberof WeeklyLifeScoreData
   */
  seekclarity?: string
  /**
   *
   * @type {number}
   * @memberof WeeklyLifeScoreData
   */
  submittedScoreCount?: number
  /**
   *
   * @type {string}
   * @memberof WeeklyLifeScoreData
   */
  time?: string
}
