/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ZoneOffsetTransition } from './zone-offset-transition'
import { ZoneOffsetTransitionRule } from './zone-offset-transition-rule'

/**
 *
 * @export
 * @interface ZoneRules
 */
export interface ZoneRules {
  /**
   *
   * @type {boolean}
   * @memberof ZoneRules
   */
  fixedOffset?: boolean
  /**
   *
   * @type {Array<ZoneOffsetTransitionRule>}
   * @memberof ZoneRules
   */
  transitionRules?: Array<ZoneOffsetTransitionRule>
  /**
   *
   * @type {Array<ZoneOffsetTransition>}
   * @memberof ZoneRules
   */
  transitions?: Array<ZoneOffsetTransition>
}
