/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ZoneOffset } from './zone-offset'

/**
 *
 * @export
 * @interface ZoneOffsetTransitionRule
 */
export interface ZoneOffsetTransitionRule {
  /**
   *
   * @type {number}
   * @memberof ZoneOffsetTransitionRule
   */
  dayOfMonthIndicator?: number
  /**
   *
   * @type {string}
   * @memberof ZoneOffsetTransitionRule
   */
  dayOfWeek?: ZoneOffsetTransitionRuleDayOfWeekEnum
  /**
   *
   * @type {string}
   * @memberof ZoneOffsetTransitionRule
   */
  localTime?: string
  /**
   *
   * @type {boolean}
   * @memberof ZoneOffsetTransitionRule
   */
  midnightEndOfDay?: boolean
  /**
   *
   * @type {string}
   * @memberof ZoneOffsetTransitionRule
   */
  month?: ZoneOffsetTransitionRuleMonthEnum
  /**
   *
   * @type {ZoneOffset}
   * @memberof ZoneOffsetTransitionRule
   */
  offsetAfter?: ZoneOffset
  /**
   *
   * @type {ZoneOffset}
   * @memberof ZoneOffsetTransitionRule
   */
  offsetBefore?: ZoneOffset
  /**
   *
   * @type {ZoneOffset}
   * @memberof ZoneOffsetTransitionRule
   */
  standardOffset?: ZoneOffset
  /**
   *
   * @type {string}
   * @memberof ZoneOffsetTransitionRule
   */
  timeDefinition?: ZoneOffsetTransitionRuleTimeDefinitionEnum
}

export const ZoneOffsetTransitionRuleDayOfWeekEnum = {
  Monday: 'MONDAY',
  Tuesday: 'TUESDAY',
  Wednesday: 'WEDNESDAY',
  Thursday: 'THURSDAY',
  Friday: 'FRIDAY',
  Saturday: 'SATURDAY',
  Sunday: 'SUNDAY'
} as const

export type ZoneOffsetTransitionRuleDayOfWeekEnum =
  typeof ZoneOffsetTransitionRuleDayOfWeekEnum[keyof typeof ZoneOffsetTransitionRuleDayOfWeekEnum]
export const ZoneOffsetTransitionRuleMonthEnum = {
  January: 'JANUARY',
  February: 'FEBRUARY',
  March: 'MARCH',
  April: 'APRIL',
  May: 'MAY',
  June: 'JUNE',
  July: 'JULY',
  August: 'AUGUST',
  September: 'SEPTEMBER',
  October: 'OCTOBER',
  November: 'NOVEMBER',
  December: 'DECEMBER'
} as const

export type ZoneOffsetTransitionRuleMonthEnum =
  typeof ZoneOffsetTransitionRuleMonthEnum[keyof typeof ZoneOffsetTransitionRuleMonthEnum]
export const ZoneOffsetTransitionRuleTimeDefinitionEnum = {
  Utc: 'UTC',
  Wall: 'WALL',
  Standard: 'STANDARD'
} as const

export type ZoneOffsetTransitionRuleTimeDefinitionEnum =
  typeof ZoneOffsetTransitionRuleTimeDefinitionEnum[keyof typeof ZoneOffsetTransitionRuleTimeDefinitionEnum]
