/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ZoneRules } from './zone-rules'

/**
 *
 * @export
 * @interface ZoneId1
 */
export interface ZoneId1 {
  /**
   *
   * @type {string}
   * @memberof ZoneId1
   */
  id?: string
  /**
   *
   * @type {ZoneRules}
   * @memberof ZoneId1
   */
  rules?: ZoneRules
}
