/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Duration } from './duration'
import { ZoneOffset } from './zone-offset'

/**
 *
 * @export
 * @interface ZoneOffsetTransition
 */
export interface ZoneOffsetTransition {
  /**
   *
   * @type {string}
   * @memberof ZoneOffsetTransition
   */
  dateTimeAfter?: string
  /**
   *
   * @type {string}
   * @memberof ZoneOffsetTransition
   */
  dateTimeBefore?: string
  /**
   *
   * @type {Duration}
   * @memberof ZoneOffsetTransition
   */
  duration?: Duration
  /**
   *
   * @type {boolean}
   * @memberof ZoneOffsetTransition
   */
  gap?: boolean
  /**
   *
   * @type {string}
   * @memberof ZoneOffsetTransition
   */
  instant?: string
  /**
   *
   * @type {ZoneOffset}
   * @memberof ZoneOffsetTransition
   */
  offsetAfter?: ZoneOffset
  /**
   *
   * @type {ZoneOffset}
   * @memberof ZoneOffsetTransition
   */
  offsetBefore?: ZoneOffset
  /**
   *
   * @type {boolean}
   * @memberof ZoneOffsetTransition
   */
  overlap?: boolean
}
